### ISSUE TITLE
Modification Subtab (on Project Details) - Order Requests by Date

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#100]
Please update the Modification Subtab so that all requests are ordered by date, with oldest first (top) and most recent last (bottom). This is similar to issue #94 

An example of the current system is shown below in which this ordering has not been applied:
image:
![image](https://cloud.githubusercontent.com/assets/4098544/5939089/c3caa73c-a6ce-11e4-9d53-288498a472df.png)

**Comment by kanglu666** [comment]
updated

**Comment by slmessier** [comment]
validated successfully - marked as "ready for Staging"

**Comment by slmessier** [comment]
**Tad has requested that the order of the grid be reversed, to show the most recent dates first**
![image](https://cloud.githubusercontent.com/assets/4098544/6596921/2a420ce6-c7cf-11e4-84c7-fe3b42ecb0ed.png)

**Comment by kanglu666** [comment]
done for both mod and non-mod

**Comment by Tad-Daniel** [comment]
This item is complete
