### ISSUE TITLE
QA3 PDF Report - Remove Comma character from User names on Form

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#101]
Remove the Comma character that is being populated within the character strings for all user information - note instances below:

page 1
![image](https://cloud.githubusercontent.com/assets/4098544/5940314/3535da5a-a6d8-11e4-8acf-75156433a789.png)

page 2
![image](https://cloud.githubusercontent.com/assets/4098544/5939795/b6362668-a6d4-11e4-8aad-063bb56b1699.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validated successfully - will be updated to "Ready for Staging"

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
