### ISSUE TITLE
QA3 PDF Report - Activity Location Checkboxes - Revisions

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#102]
Within the QA3 PDF report, the text associated with the Activity Location checkboxes is being truncated. Please update to match the text - as well as the general aesthetic layout -  of the checkboxes from the UI. See below:

QA3 PDF Report - the highlighted changes were identified by comparing to the layout of the UI:
![image](https://cloud.githubusercontent.com/assets/4098544/5940901/b1d04c00-a6db-11e4-9095-266d77f2dd96.png)

UI:
![image](https://cloud.githubusercontent.com/assets/4098544/5940533/800529d6-a6d9-11e4-9386-4f8aa6f429e8.png)

**Comment by kanglu666** [comment]
updated

**Comment by slmessier** [comment]
Thank you for making the updates above. However this layout still requires some additional adjustment - see the list below, using the color coding to associate each adjustment request to each element of the form:

![image](https://cloud.githubusercontent.com/assets/4098544/6061239/fb7f034e-ad13-11e4-97d8-eda9c6173053.png)

**Comment by kanglu666** [comment]
updated except: "100-foot buffer - (non-tidal werland of sepecial State concern)"  it's too long to put in one line.

**Comment by slmessier** [comment]
Please wrap the text to a second line and adjust the grid if necessary. All text is required to exist on the form.

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validated successfully - updated to "Ready for Staging"

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
