### ISSUE TITLE
QA3 PDF Report - Populate "Submitted to Rec/QA" triggered by Package Status = "Approved"

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#103]
**On the QA3 PDF Report - the value for the field "Submitted to REC/QA" is to be populated specifically after a Package Approver has Approved the Package.** Currently, the system is erroneously populating too early in the workflow (at the point when a REC/QA representative is associated on the Modification Request Form). Additionally, the value that is populated within the report is the user that ultimately approves the package, which could be any user with Package Approver permission, and will not always be the REC/QA representative that is associated intially through the Modification Request Form.
Current Report after Modification Request Form is submitted - (erroneous):
![image](https://cloud.githubusercontent.com/assets/4098544/5942401/552fb99a-a6e5-11e4-98ff-2474219d0dfb.png)

Please see the itemized updates below:
1. Update the system to **populate the associated value on the report using the intended trigger - when package status = approved, after the re-authentication stage.**
2. Update the system to **populate using the value of the user name that has updated the Package Status = Approved** (this could be different than the user name associated during the Modification Request Form workflow.
3. Update the system to **populate the "Date" field on the report with the date/time value when the user has updated the Package Status - Approved, after the re-authentication stage.**

![image](https://cloud.githubusercontent.com/assets/4098544/5942392/39e45c18-a6e5-11e4-9107-6803e973e033.png)

**Comment by kanglu666** [comment]
database updated, report updated. please test

**Comment by slmessier** [comment]
The report is not being populated as expected. Please see the graphics below to reference the workflow that triggers the form to be populated and the outcome within the form:

Trigger:
![image](https://cloud.githubusercontent.com/assets/4098544/6062129/3864c09e-ad1b-11e4-9f11-d6f1afa4e780.png)


Outcome
![image](https://cloud.githubusercontent.com/assets/4098544/6062135/41610e64-ad1b-11e4-8a59-06dc95ff1afb.png)

**Comment by kanglu666** [comment]
done. please test

**Comment by slmessier** [comment]
validated successfully - updated to "Ready for Staging"

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
