### ISSUE TITLE
Modification Response Form - Validation Message Text for Package = Approved

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#104]
Update the text of the validation message (shown below) which is issued when the user has updated package status to Approved but has not yet selected an agency approval group checkbox.

Update text to - "Packages forwarded for review require at least 1 approval group selection." (remove the word "with)
![image](https://cloud.githubusercontent.com/assets/4098544/5943116/42766ede-a6ea-11e4-9a02-fc34af0644e8.png)

**Comment by kanglu666** [comment]
updated

**Comment by slmessier** [comment]
validated successfully in KCI DEV - updated to Ready for Staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
