### ISSUE TITLE
QA3 PDF Report - Update Trigger to Populate Agency Approvals Upon Re-Authentication

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#105]
The system should populate the Agency Approval fields of the QA3 PDF report (**with user and date**) when each of the Agency dropdowns have bene updated to "approved" - **specifically triggered by successful execution of the re-authentication process**. 

See the mappings within the graphics below:

PDF Report:
![image](https://cloud.githubusercontent.com/assets/4098544/5943925/cbb28876-a6f0-11e4-8ac8-c71570ea030b.png)

UI Dropdown on Modification Response Form:
![image](https://cloud.githubusercontent.com/assets/4098544/5944023/bc502b12-a6f1-11e4-95df-fc0de91baba8.png)

**Comment by kanglu666** [comment]
not sure you mean populating with incorrect user.
there is no  re-authentication process for each Agency dropdowns have bene updated to "approved".
need to  update the design.

**Comment by slmessier** [comment]
this issue may be obsolete or revised pending resolution of issue #95. It will remain open until that time when it can be assessed further.

**Comment by slmessier** [comment]
The system has been updated to be triggered appropriately. 

However, the system is populating the value with the incorrect user name:

Agency Approval via UI:
![image](https://cloud.githubusercontent.com/assets/4098544/6062331/e63675e0-ad1c-11e4-8ad9-4dbbd7830355.png)

PDF Form (Incorrect currently)
![image](https://cloud.githubusercontent.com/assets/4098544/6062309/bd85081e-ad1c-11e4-9b45-ac1742032450.png)

**Comment by kanglu666** [comment]
working fine on my side, we need to work through this together

**Comment by kanglu666** [comment]
updated, please test

**Comment by slmessier** [comment]
validated in KCI DEV - updated to Ready for Staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
