### ISSUE TITLE
QA3 PDF Report - Spelling Mistake "Contractor"

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#106]
Please fix the spelling of Contractor on the form - identified in graphic below:
![image](https://cloud.githubusercontent.com/assets/4098544/6062020/77c6fd3e-ad1a-11e4-8de0-07a1eb762d4e.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
I still seeing the incorrect spelling

**Comment by kanglu666** [comment]
updated

**Comment by slmessier** [comment]
validated successfully - updated to "Ready for Staging"

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
