### ISSUE TITLE
QA3 PDF Report - Populate "Contractor" & "SHA Project Engineer" triggered by Re-Authentication on Modification Request Form

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#107]
the following fields of the QA3 report are not being populated completely:

1. Contractor Time Stamp
2. SHA Project Engineer
3. SHA Project Engineer Time Stamp

![image](https://cloud.githubusercontent.com/assets/4098544/6129107/ca41aeb8-b109-11e4-986b-f3f95da2395c.png)

Trigger:
These values of the QA3 PDF form should become populated when the associated users successfully complete the re-authentication process using the Modification Request Form:
![image](https://cloud.githubusercontent.com/assets/4098544/6129153/23d5d65c-b10a-11e4-9fd0-8a501879f039.png)

**Comment by kanglu666** [comment]
just work through the work flow, it's working fine for me.
looking the record you have, looks like your record data has some issue, please create new record to test.

**Comment by slmessier** [comment]
this issue appears to be nearly resolved. the only outstanding item is that the REC/QA username & timestamp is being populated using an incorrect trigger

![image](https://cloud.githubusercontent.com/assets/4098544/6135000/1bad8816-b133-11e4-8ec9-61ef98f7e6fa.png)

Trigger - Package Status - Approved, Authenticated, Submitted (Saved):
![image](https://cloud.githubusercontent.com/assets/4098544/6135044/611c4360-b133-11e4-8c7a-452a642cc331.png)

**Comment by kanglu666** [comment]
updated

**Comment by slmessier** [comment]
validated successfully in KCI DEV - Updated to Ready for Staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
