### ISSUE TITLE
Modification Response Form - Replace Text of "Cancel" Button with "Close"

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#108]
Please replace the text of the "Cancel" button with "Close" for the Modification Response Form
![image](https://cloud.githubusercontent.com/assets/4098544/6129211/8f57b1e8-b10a-11e4-92df-fccf4e80265b.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validate successfully in KCI DEV - updated to Ready for Staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
