### ISSUE TITLE
Modification Request Form - Editing Functionality &Submit Button Should Persist when Package Status  "Pre-Submittal"

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#109]
The Modification Request Form should remain fully editable when Package Status - Pre-Submittal. Currently the system displays all input fields on the form as disabled if the user has clicked submit. However, the entire form should remain editable for as long as Package Status = "Pre-Submittal".

**Please update the system to perform an additional check prior to disabling the field of the Modification Request Form, to check for Package Status. 
1. If Package Status - "Pre-Submittal", then the fields would remain enabled. 
2. If the Package Status <> "Pre-Submittal", then all fields should be disabled.**

![image](https://cloud.githubusercontent.com/assets/4098544/6129866/47d65e5a-b10f-11e4-826e-39472ba334f2.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validated successfully in KCI DEV - updated to Ready for Staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
