### ISSUE TITLE
Project List - Mods Column Value - Display Value for Last Dated Request

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#110]
Within the Project List, the Mods column value should always display the Request Status **for the most recent request create date.**
![image](https://cloud.githubusercontent.com/assets/4098544/6130470/4b872364-b113-11e4-874d-e55b1028798d.png)

The value shown in the graphic is erroneous as it does not represent the value from latest request create date.

![image](https://cloud.githubusercontent.com/assets/4098544/6130531/a1ac9030-b113-11e4-845b-613ef921926c.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validate successfully in KCI DEV - updated to Ready for Staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
