### ISSUE TITLE
All Toolkits - Update Base URLS within Staging Environment to Provide Internet Access

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#111]
Please update the base URLS as they exist within the STAGING environment so that Staging can be accessed through the internet.

After this has been done, please assign this issue to @slmessier and I can test/confirm access using SHA VPN.

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
