### ISSUE TITLE
EM Toolkit & MDE Toolkit - Unable to Add New Users

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#113]
The system is producing the following error message when attempting to add a new user account to the EM & MDE Toolkit.

Same message appears for both of the EM and MDE Toolkits:
![image](https://cloud.githubusercontent.com/assets/4098544/6215905/e3078e18-b5d2-11e4-934e-0db6e4378e77.png)

**Comment by kanglu666** [comment]
fixed at KCI, please test

**Comment by slmessier** [comment]
validated successfully in KCI-DEV - updated to "Ready for Staging"

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
