### ISSUE TITLE
QA Toolkit - Project List PDF Report - Add User Office Phone to Users Section

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#114]
The User phone # should be added to the Project List Report:

2. **Remove the Title Column and shift columns to the left**
![image](https://cloud.githubusercontent.com/assets/4098544/6288239/7e6a3468-b8e5-11e4-8eff-30fa2cb52e6c.png)

1. **Add User Office Phone to the PDF report as the right-most column:**
![image](https://cloud.githubusercontent.com/assets/4098544/6288185/257cbe3e-b8e5-11e4-8d41-ed070a163c67.png)

**Comment by kanglu666** [comment]
updated at KCI, please test

**Comment by slmessier** [comment]
validated successfully in KCI DEV - updated to Ready for Staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
