### ISSUE TITLE
QA Toolkit - QA3 PDF Report - Align User Name values Vertically

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#115]
Please update the user name values that are populated by the system within the approval signatures section of the report. Begin all values from the location of the red line shown in the graphic below:
![image](https://cloud.githubusercontent.com/assets/4098544/6305355/a4e95958-b8f8-11e4-8376-f74862068bbd.png)

**Comment by kanglu666** [comment]
updated at KCi please test

**Comment by slmessier** [comment]
This looks good but the Final Modification Request Status value should be in-line with the other values as well:

![image](https://cloud.githubusercontent.com/assets/4098544/6400370/6ce70686-bdc6-11e4-95c6-4ac1ccce0113.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validated successfully in KCI DEV - updated to Ready for Staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
