### ISSUE TITLE
QA Toolkit - QA3 PDF Report - Update the Format for All Timestamps - MM/DD/YYYY

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#116]
Update timestamp values to use a consistent format for all timestamps within the form
1. exclude Hours, Minutes, & Seconds
2. use 2-digit month & day, 4-digit year format - MM/DD/YYYY (correctly shown in red box below)
![image](https://cloud.githubusercontent.com/assets/4098544/6306051/0040c3cc-b8fe-11e4-8116-4c3a291ba6f1.png)

**Comment by kanglu666** [comment]
updated at KCi please test

**Comment by slmessier** [comment]
validated successfully in KCI DEV - updated to Ready for Staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
