### ISSUE TITLE
QA Toolkit - Admin Menu: User Edit Screen - Environmental Programs Checkbox does not Persist

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#117]
Within the Admin:Edit User menu, the Environmental Programs Checkbox does not remain checked after being selected and saved.

1. check the checkbox for a given user account
2. click save
3. the system will not persist displaying the checkbox as selected

![image](https://cloud.githubusercontent.com/assets/4098544/6308843/a7d6485c-b915-11e4-8b8d-21515c354c15.png)

**Comment by kanglu666** [comment]
updated at KCI please test

**Comment by slmessier** [comment]
validated successfully in KCI DEV - updated to Ready for Staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
