### ISSUE TITLE
QA Toolkit - Admin Menu: User Edit Screen - Spelling Correction: "Environmental Programs"

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#118]
Please update the spelling of the Environmental Programs checkbox (currently is displayed incorrectly as "Environmental Problems")

![image](https://cloud.githubusercontent.com/assets/4098544/6308898/182dcfda-b916-11e4-9d19-ff14e45224b4.png)

**Comment by kanglu666** [comment]
updated at KCI please test

**Comment by slmessier** [comment]
validated successfully in KCI DEV - updated to Ready for Staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
