### ISSUE TITLE
Modification Response Form - Error Message - Spelling Correction: "required"

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#119]
Please **correct the spelling of "required"** within the error messages that the system displays when the user has not yet "signed" using the re-authentication log-in prompt.

**The message occurs in 2 distinct workflows:
1. After Package Approver has updated Package Status = "Package Approved"
2. After Agency Request Approvers (for all agencies) have updated Request Status = "Approved"**

After **Package Status = "Package Approved"**:
![image](https://cloud.githubusercontent.com/assets/4098544/6327823/6fbd4ae0-bb2e-11e4-8da1-649ce45a574a.png)

After **Agency Request = "Approved"**:
![image](https://cloud.githubusercontent.com/assets/4098544/6327835/954b7fca-bb2e-11e4-821d-149e110d91ce.png)

**Comment by kanglu666** [comment]
updated at KCI please test

**Comment by slmessier** [comment]
The system is still displaying "requied" instead of the correct spelling, "requi**r**ed"

**Comment by kanglu666** [comment]
everything look fine at my side. please give me a step by step work through or a sceen

**Comment by slmessier** [comment]
validated successfully in KCI DEV - updated to Ready for Staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
