### ISSUE TITLE
Modification Response Form - Update UI Control for Overall Request Status

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#120]
Since overall request is read-only and updated exclusively by the system, please:
**1. Update the text label - change "Overall Request Status" to "Final Modification Request Status"
2. Remove the dropdown menu control and replace with a simple read-only text string. Use bold & italics to display the text value**

See graphics below:

**Current:**
![image](https://cloud.githubusercontent.com/assets/4098544/6328856/8f21707c-bb39-11e4-8f32-f98f94f74d66.png)

**Enhanced:**
![image](https://cloud.githubusercontent.com/assets/4098544/6329045/028d8ff4-bb3b-11e4-99be-7f6d8251f309.png)

**Comment by kanglu666** [comment]
updated at KCI please test

**Comment by slmessier** [comment]
Please also remove the dropdown menu. The string should be displayed as a plan black text label. see the graphic above.

**Comment by kanglu666** [comment]
the dropdown menu is tied to the status table in the database (a list of status key and value), a single string textbox can't do that. keep it as is.

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
please update the control to remove the text box entirely, so that the the text string appears similar to a text label on the UI

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validated successfully in KCI DEV - updated to Ready for Staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
