### ISSUE TITLE
QA Toolkit - Request & All Related Responses Become Read-only upon Approval or Denial

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#122]
**Update the system so that a Request becomes read-only after Final Modification Request Status = Approved OR Denied.**

**The following  components should become read-only** after a given request (Final Modification Request Status) is approved or denied:
**1. The original request - Modification Request Form
2. All responses to the original request - Modification Response Form(s)**

**Comment by kanglu666** [comment]
Just checked and confirmed that the existing Modification Request Forms and existing Modification Response Form(s) are ready-only when the Request Status = Approved OR Denied.

**Comment by slmessier** [comment]
Please **update the system so that the *Edit Modification Icon* is removed or disabled when the Final Modification Request Status is updated to APPROVED or DENIED.** This update should prevent users from contributing additional responses after a request has reached approval or denial.

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validated successfully in KCI DEV - updated to Ready for Staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
