### ISSUE TITLE
Modification Response Form - Update Logic that Populates Email Notification Recipients

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#123]
As per the original design, the system should include logic to automatically populate recipients for email notifications. Reference the logic indicated in Green in each of the screen shots below.

**For the Modification Request Form (Initial Notification):**
![image](https://cloud.githubusercontent.com/assets/4098544/6330717/c6a574bc-bb48-11e4-9928-ef9563553d70.png)

**For the Modification Response Form (All Secondary Notifications):**
![image](https://cloud.githubusercontent.com/assets/4098544/6330835/926c1ede-bb49-11e4-8dff-ce1d64c988f5.png)

Currently, the system fails to automatically populate with recipients from previous notifications (#1 of Modification Response Form logic).

**Comment by kanglu666** [comment]
done, please test

**Comment by slmessier** [comment]
The Modification Response form appears to have been updated successfully and populates the recipients as expected.

Please also update the Modification Request Form to also account for specification number # 4 above (and identified more distinctly in blue within the graphic below):
![image](https://cloud.githubusercontent.com/assets/4098544/6485962/867e787a-c255-11e4-8e17-595741950c78.png)

**Comment by kanglu666** [comment]
done at kci

**Comment by slmessier** [comment]
Please add additional logic to the _Modification Response Form_ for including all users with _Package Approver_ capability

**Comment by kanglu666** [comment]
done, please test

**Comment by slmessier** [comment]
validated in KCI DEV successfully - Updated to Ready for Staging

**Comment by slmessier** [comment]
Tad - I believe this issue was resolved some time ago. Please confirm and close if applicable.

**Comment by Tad-Daniel** [comment]
issue resolved
