### ISSUE TITLE
Modification Request Form - Update Trigger to Display as Read-Only

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#124]
Update the existing system trigger that changes the form read-only.

Currently Existing Trigger:
-when "Contractor", "SHA Project Engineer", & "REC/QA" representatives have been successfully populated.

New Trigger:
-when the package status = “Package Approved” OR "Package Withdrawn"

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validated successfully - updated to Ready for Staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
