### ISSUE TITLE
QA Toolkit - Project Details PDF Report - Updates to Aesthetic Formatting

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#125]
Stakeholders have requested the following updates to the Project Details PDF Report:

1. Remove the bounding box border from each of the "Modifications" & "Approvals" sections - indicated by green graphics

2. Update the letter casing for the Modifications & Approvals sections - indicated by orange graphics

![image](https://cloud.githubusercontent.com/assets/4098544/6334578/7c461f32-bb63-11e4-98ec-bcaf7d308848.png)

**Comment by kanglu666** [comment]
updated at KCI please test

**Comment by slmessier** [comment]
validated successfully in KCI DEV - updated to Ready for Staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
