### ISSUE TITLE
QA3 PDF Report - Add pages 3 and 4 to PDF Form Output

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#126]
**Please add pages 3 and 4** to the PDF report output:

Source PDF location - **ignore the red text font and implement using a uniform black font**: M:\2014\18145293A.004\Reports\ModificationsEnhancements\Feedback_PostUAT_Release1_20150223\QA3_Page3and4.pdf

Page 3:
![image](https://cloud.githubusercontent.com/assets/4098544/6351773/472afd00-bc0c-11e4-8946-f052bbb35bbb.png)

Page 4:
![image](https://cloud.githubusercontent.com/assets/4098544/6351784/5414931e-bc0c-11e4-8b30-9a2cb017a89f.png)

**Comment by Tad-Daniel** [comment]
This issues can be delayed a bit as I will be submitting an updated version of these documents very soon.

**Comment by slmessier** [comment]
**Please implement the following revisions for Page 3:**
![image](https://cloud.githubusercontent.com/assets/4098544/6621670/54bec416-c8ae-11e4-82fa-99f349445cf6.png)

**Please implement the following revisions for Page 4:**
![image](https://cloud.githubusercontent.com/assets/4098544/6622146/367fc0f6-c8b1-11e4-9481-e56e69c07dd6.png)

**Comment by kanglu666** [comment]
done at KCI and  SHA Staging.

**Comment by slmessier** [comment]
Please make the (1) update to Page 3 below:
![image](https://cloud.githubusercontent.com/assets/4098544/6625354/f7a9dcf8-c8c5-11e4-8163-c1bd912c623f.png)

Please make the (1) update to Page 4 below:
![image](https://cloud.githubusercontent.com/assets/4098544/6625584/5d89b132-c8c7-11e4-9161-ca7a76236bab.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
these issues have been validated in STAGING & SHA PRODUCTION. This issue will be closed.
