### ISSUE TITLE
QA3 PDF Report - Assess System Capability for Dynamic Display of Agency Approval Lines

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#127]
Stakeholders have expressed a preference to dynamically display the Agency Approval Lines within the QA3 PDF form if possible - meaning that the lines are not displayed on the PDF at all in the case when the user has not selected the associated checkbox using the system UI.

**Please assess whether this capability is something that can be implemented within the system.**

**See the example below:**
Note: only QA Program is selected through system UI
![image](https://cloud.githubusercontent.com/assets/4098544/6352241/306e5186-bc0f-11e4-9866-d4483ac5386f.png)

PDF Output Mockup (page 2):
![image](https://cloud.githubusercontent.com/assets/4098544/6352226/16633f0e-bc0f-11e4-937e-62e1da144b37.png)

**Comment by slmessier** [comment]
Logging the secondary alternative below as a backup solution. **Stakeholders' preference is to dynamically load the form so that should be the solution if it is feasible.**

**Secondary Alternative - Populate all Agency Approvals that to do apply with the text "NA"**

**Comment by kanglu666** [comment]
updated at KCI please test

**Comment by slmessier** [comment]
Secondary option has been implemented and validated successfully in KCI DEV - updated to Ready for Staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
