### ISSUE TITLE
QA3 PDF Report - Revisions to Page 2

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#128]
**Please implement the following updates to Page 2 of the QA3 PDF Report. Reference the items in red text within the associated graphic:**

1. Replace "Submitted to REC/QA" with "Submitted to QA Program"
2. Insert a new line for "Final Modification Request Status" and populate with the current request status value
3. Replace "REC/QA" text and "SHA-PE" text with "QA Program" and "SHA Project Engineer" respectively

![image](https://cloud.githubusercontent.com/assets/4098544/6352430/a4d5e7fe-bc10-11e4-8d9c-c97e97c88cde.png)

**Comment by kanglu666** [comment]
updated at KCI please test

**Comment by slmessier** [comment]
Please also update the "Submitted to REC/QA" text to "Submitted to QA Program"

![image](https://cloud.githubusercontent.com/assets/4098544/6401349/bc11a19c-bdcd-11e4-9779-624b36eb3075.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validated successfully in KCI DEV - updated to Ready for Staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
