### ISSUE TITLE
QA3 PDF Report - Update Font styling for all populated values

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#129]
Please remove the underline from the font styling that is used to populate values within the QA3 PDF Form. Also remove any bold or italic font if it exists within the current configuration.

**Comment by kanglu666** [comment]
updated at KCI please test

**Comment by slmessier** [comment]
validated successfully in KCI DEV - updated to Ready for Staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
