### ISSUE TITLE
EM Toolkit - Systematic Update - Remove / Update "ram-corp" solution hyperlink from all screens

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#13]
The ram-corp hyperlink that is displayed at the far bottom of each page should be removed or updated. If the preference is to update, the specifications for the new hyperlink have yet to be defined.

**Comment by slmessier** [comment]
Please remove all text from this area completely

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
Validated successfully - will update to "Ready for Staging"

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
