### ISSUE TITLE
QA3 PDF Report & Modification Request Form - Activity Location Checkbox Section - Revisions

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#130]
Stakeholders have requested the following enhancements to the Activity Location checkbox section.

**Update both the QA3 PDF Form template and the Modification Request Form** with the following enhancements:
1. **Add a new checkbox for "AASCD"** between "Tidal Wetlands" and "Critical Area" - highlighted in green in the graphics below
2. **Add a new checkbox for "Stormwater Management"** below "100 year floodplain" - highlighted in blue in the graphics below
3. Remove the parenthetical text associated with Critical Area checkbox - **remove text "(e.g. mudflat, vegetated shallows)”**

**Modification Request Form Revisions Mockup:**
![image](https://cloud.githubusercontent.com/assets/4098544/6354408/48dd5380-bc1d-11e4-8c3a-8e801e3b5057.png)

**QA3 PDF Form Revisions Mockup:**
![image](https://cloud.githubusercontent.com/assets/4098544/6354663/e49909da-bc1e-11e4-8cdc-4dbfe53b18db.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
1. On the QA3 PDF Form - Please display all values using the standard, black font color. Apologies for not communicating clearly 
![image](https://cloud.githubusercontent.com/assets/4098544/6414249/ed6c5ffc-be63-11e4-98d3-fcf1801e271e.png)

1. The UI Modification Request form has not been updated 
![image](https://cloud.githubusercontent.com/assets/4098544/6414301/4b6f41b4-be64-11e4-82c7-8ad2c7cbb30d.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validated successfully in KCI DEV - updated to Ready for Staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
