### ISSUE TITLE
QA3 PDF Report - Agency Approval Values

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#131]
Please update the system to automatically populate the Agency Approval lines with values according to following logic - reference the graphic below:
**1. Insert text: "Awaiting Review" in the case when an Agency Approval is required and status = "Submitted for Approval"
2. Insert text: "DENIED" (in all capital letters) in the case when an Agency Approval status = "Denied". Include the timestamp**

![image](https://cloud.githubusercontent.com/assets/4098544/6355307/00428dd8-bc23-11e4-92d1-f83ed0b89b47.png)

**Comment by kanglu666** [comment]
i can do this with DB side update. So no longer need the report layout change unless they do need the status column to show.

**Comment by slmessier** [comment]
Please proceed with updating according to the original specifications above - thank you!

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validated successfully in KCI DEV - updated to Ready for Staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
