### ISSUE TITLE
QA3 PDF Report - Modification Number Value

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#132]
The value that is being populated within the "Modification Number" text field within the report should be updated so that the modification number always begins at 1 for a single project, and then increases by one for each new request  that is associated to the same project.

This may require slight re-architecture of the database in order to support the requested functionality.
![image](https://cloud.githubusercontent.com/assets/4098544/6357057/a5a990c6-bc2f-11e4-92ad-f91e120fd655.png)

**Comment by kanglu666** [comment]
database/report updated, please test

**Comment by slmessier** [comment]
validated successfully in KCI DEV - updated to Ready for Staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
