### ISSUE TITLE
QA Toolkit - Project List Grid - Update Aesthetic Layout & Text Formatting

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#134]
Please implement the following enhancements to the Project List Grid:
1. Update "E&S Permit" column heading label to "E&S Per." and decrease the horizontal width of the column
2. Update "District" column heading label to "Dist." and decrease the horizontal width of the column
3. Update "County" column heading label to "Co." and decrease the horizontal width of the column
4. Abbreviate county values displayed within the "Co." column - this may require a new field in the model.
![image](https://cloud.githubusercontent.com/assets/4098544/6358960/573d0086-bc3d-11e4-84e5-a244ecc26170.png)

![image](https://cloud.githubusercontent.com/assets/4098544/6359035/f859c4c2-bc3d-11e4-909b-97942913f219.png)

**Comment by kanglu666** [comment]
DONE

**Comment by slmessier** [comment]
(All updates to the text look good.)
- Decrease the horizontal width of each of the columns so that the width accommodates the heading text without any additional space.
  - *E&S Per.*
  - *Co.*
  - *Dist.*
- Increase the horizontal space of the *Mods* column using the space that is recovered by decreasing the columns listed above.

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
