### ISSUE TITLE
QA Toolkit - Update System Role Permissions: Contractor

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#136]
**Please update the functional capabilities associated with the *Contractor* System Role:**

- **Add access to the Projects Tab to view the Project List**
  - Currently accessible tabs for *Contractor* role 
![image](https://cloud.githubusercontent.com/assets/4098544/6373930/ba6e583c-bcdb-11e4-85c5-c0d22377cb02.png)
  - Enhanced accessible tabs for *Contractor* role (similar to original capabilities of *Inspector* role)
![image](https://cloud.githubusercontent.com/assets/4098544/6373974/e7d717fa-bcdb-11e4-8db4-a464759d6d83.png)

- **Add the capability to Edit Project Details on the Project List Screen**
  - Current *Contractor* role capabilities for Project Details - (none; not currently available)
  - Enhanced *Contractor* role capabilities for Project Details (similar to the original capabilities of the *Power Reviewer* system role)
![image](https://cloud.githubusercontent.com/assets/4098544/6374498/484f3c40-bcdf-11e4-9878-32833a145f82.png)

- **On the Project Details screen, enable editing capabilities exclusively for the *"Mods"* & *"Approvals"* subtabs**
  - This may be accomplished by enabling edit capabilities for the 2 referenced subtabs in particular **OR** alternatively by restricting editing capabilities for all subtabs except for the 2 referenced subtabs. Use your own discretion to determine the preferred approach.
  - ![image](https://cloud.githubusercontent.com/assets/4098544/6374585/df0c5654-bcdf-11e4-863e-c5fb1705d3d2.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
Please update to also disable editing for project general information

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validated successfully in KCI DEV - update to Ready for Staging

**Comment by slmessier** [comment]
Please **update the system to disable editing functionality for the control shown within the graphic below**, which remains editable currently. This update applies to all (5) enhanced system roles.
![image](https://cloud.githubusercontent.com/assets/4098544/6507172/39f61570-c31e-11e4-90a7-cafdbf989f9c.png)

**Comment by kanglu666** [comment]
i can't disable the popup, but i can disable the save and delete button in the pop up, already done, please test.

**Comment by slmessier** [comment]
this issue was initially implemented and tested in spring of 2015 and was successfully validated again by Scott M. on 2/1/2016 as part of a GitHub housekeeping clean-up effort. the issue will be closed.
