### ISSUE TITLE
QA Toolkit - Update System Role Permissions: Project Engineer

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#137]
**Please update the functional capabilities associated with the *Project Engineer* System Role:**

- **Add the capability to Edit Project Details on the Project List Screen**
  - Current *Project Engineer* role capabilities for Project Details 
![image](https://cloud.githubusercontent.com/assets/4098544/6376937/09392d62-bcef-11e4-9e86-f097ca1435d9.png)

  - Enhanced *Project Engineer* role capabilities for Project Details 
![image](https://cloud.githubusercontent.com/assets/4098544/6374498/484f3c40-bcdf-11e4-9878-32833a145f82.png)

- **On the Project Details screen, enable editing capabilities exclusively for the following (5) subtabs**
  - *1. "QA Incentives"*
  - *2. "Sheets/Plates"*
  - *3. "Documents"*
  - *4. "Mods"*
  - *5. "Approvals"*
  - This may be accomplished by enabling edit capabilities for the 5 referenced subtabs in particular **OR** alternatively by restricting editing capabilities for all subtabs except for the 5 referenced subtabs. Use your own discretion to determine the preferred approach.
  - ![image](https://cloud.githubusercontent.com/assets/4098544/6377129/2307716c-bcf0-11e4-903f-76c345660e10.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
Please update to also disable editing for project general information

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validated successfully in KCI DEV - update to Ready for Staging

**Comment by slmessier** [comment]
Please **update the system to disable editing functionality for the control shown within the graphic below**, which remains editable currently. This update applies to all (5) enhanced system roles.
![image](https://cloud.githubusercontent.com/assets/4098544/6507172/39f61570-c31e-11e4-90a7-cafdbf989f9c.png)

**Comment by kanglu666** [comment]
i can't disable the popup, but i can disable the save and delete button in the pop up, already done, please test.

**Comment by slmessier** [comment]
this issue was initially implemented and tested in spring of 2015 and was successfully validated again by Scott M. on 2/1/2016 as part of a GitHub housekeeping clean-up effort. the issue will be closed.
