### ISSUE TITLE
QA Toolkit - Update System Role Permissions: Reviewer

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#140]
**Please update the functional capabilities associated with the *Reviewer* System Role:**

- **Add the capability to Edit Project Details on the Project List Screen**
  - Current *Reviewer* role capabilities for Project Details 
![image](https://cloud.githubusercontent.com/assets/4098544/6373003/ce8f63e8-bcd5-11e4-9cdc-c44fe24f5ad0.png)

  - Enhanced *Reviewer* role capabilities for Project Details 
![image](https://cloud.githubusercontent.com/assets/4098544/6373164/0ff1246a-bcd7-11e4-8192-1282003f2c1a.png)

- **On the Project Details screen, enable editing capabilities exclusively for the *"Mods"* & *"Approvals"* subtabs**
  - This may be accomplished by enabling edit capabilities for the 2 referenced subtabs in particular **OR** alternatively by restricting editing capabilities for all subtabs except for the 2 referenced subtabs. Use your own discretion to determine the preferred approach.
  - ![image](https://cloud.githubusercontent.com/assets/4098544/6374585/df0c5654-bcdf-11e4-863e-c5fb1705d3d2.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
Please update to also disable editing for project general information

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validated successfully in KCI DEV - update to Ready for Staging

**Comment by slmessier** [comment]
Please **update the system to disable editing functionality for the control shown within the graphic below**, which remains editable currently. This update applies to all (5) enhanced system roles.
![image](https://cloud.githubusercontent.com/assets/4098544/6507172/39f61570-c31e-11e4-90a7-cafdbf989f9c.png)

**Comment by kanglu666** [comment]
i can't disable the popup, but i can disable the save and delete button in the pop up, already done, please test.

**Comment by Tad-Daniel** [comment]
item complete
