### ISSUE TITLE
QA3 PDF Report - Capitalize Text Value for Final Modification Request Status

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#141]
Please update the system to populate the Final Modification Request Status value using all capital lettering:
![image](https://cloud.githubusercontent.com/assets/4098544/6414125/2bed4468-be63-11e4-8cbd-0b499b07e566.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validated successfully in KCI DEV - updated to Ready for Staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
