### ISSUE TITLE
MDE Toolkit - Increase Attachment File-size Limit Configuration

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#142]
Users are attempting to upload a PDF to the MDE toolkit that has a file-size of ~30 MB. 

1. **Please investigate the existing limitations regarding file-size within the existing system and increase the upper limit to 50 MB.**

1. **Please indicate whether the updated limit will apply to all toolkits or only to the MDE Toolkit exclusively.**

1. **Please indicate whether this update can be applied to the PRODUCTION environment without a code push.**

**Comment by kanglu666** [comment]
1: done at kci , please test.
2: all toolkits
3: no code push

**Comment by slmessier** [comment]
validated successfully in KCI DEV - Please make this update in PRODUCTION ASAP

**Comment by kanglu666** [comment]
done at SHA PROD, please test

**Comment by slmessier** [comment]
Scott,

I still got timed out. I tried it twice with no luck.

Thanks,
___________________________________

Ed Tinney
Environmental Scientist

**Comment by kanglu666** [comment]
updated, just tested at SHA prod, it's working for me. please test

**Comment by slmessier** [comment]
From: Ed Tinney [mailto:etinney@rkk.com] 
Sent: Friday, March 06, 2015 2:37 PM
To: Scott Messier
Cc: Heidi Hammel
Subject: Re: PG618E21: MD 4/Suitland Parkway Interchange LOA

It worked this time! Thanks!
___________________________________

Ed Tinney
Environmental Scientist

RK&K 
on Behalf of MDE, Water Management Administration
81 W. Mosher Street
Baltimore, MD 21217

410.462.9364 D
410.728.2900 P
609.425.9498 C
