### ISSUE TITLE
QA Toolkit - Update Package Status Domain Value: "Package Approved" --> "Package Submitted"

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#143]
Please update the domain value text description for the Package Status domain:
    **Update "Package Approved: to "Package Submitted"**

![image](https://cloud.githubusercontent.com/assets/4098544/6507759/54ba47a6-c322-11e4-9162-7fd9c638f0ff.png)

![image](https://cloud.githubusercontent.com/assets/4098544/6507760/5d22ac1c-c322-11e4-8a6a-7b93334bfb69.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
this issue was initially implemented and tested in spring of 2015 and was successfully validated again by Scott M. on 2/1/2016 as part of a GitHub housekeeping clean-up effort. the issue will be closed.
