### ISSUE TITLE
QA Toolkit - Project Details - Mods Subtab - Add Horizontal Space between Package Status & Final Request Status Information

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#144]
Please update the grid on the "Mods" subtab to add additional horizontal space between the _Package Status_ and _Final Request Status_ values

From Tad:
![image](https://cloud.githubusercontent.com/assets/4098544/6508070/64c19a80-c324-11e4-9c87-46489e00bcf5.png)

Sample Mockup:
![image](https://cloud.githubusercontent.com/assets/4098544/6508134/cec6cd24-c324-11e4-8d82-2fbf2d38d901.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
this issue was initially implemented and tested in spring of 2015 and was successfully validated again by Scott M. on 2/1/2016 as part of a GitHub housekeeping clean-up effort. the issue will be closed.
