### ISSUE TITLE
QA Toolkit - Approvals Subtab - Update Text Labels

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#145]
Stakeholders are requested that the terminology for the Approvals Subtab (on Project Details) is updated to use new terminology. see itemized change below:

1. **Update the Text Label on the Subtab to "QA Concurrence"**

2. **Update the Text Label for the heading above the grid on the Subtab to "QA Concurrence"**

![image](https://cloud.githubusercontent.com/assets/4098544/6596876/bd3a4f50-c7ce-11e4-950c-8cbfe8174eec.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
this issue was initially implemented and tested in spring of 2015 and was successfully validated again by Scott M. on 2/1/2016 as part of a GitHub housekeeping clean-up effort. the issue will be closed.
