### ISSUE TITLE
Non-Modification Request Form - Updates to Layout & Text Labels

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#146]
**Tad has requested a few updates to the layout of the Non-Modification Approval Request form.**
Please find the list of updates below.

1. **Update the text of the title/heading on the page to "QA Concurrence"**

2. **Update the text of the label above the Approval dropdown to "QA Response"**

3. **Enlarge the vertical spacing of the input text box associated with the "Request Text" to roughly twice its existing vertical size.**

4. **Remove icons for delete project and update project functions**

![image](https://cloud.githubusercontent.com/assets/4098544/6597231/6daed188-c7d1-11e4-9a88-87d98178d2aa.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
this issue was initially implemented and tested in spring of 2015 and was successfully validated again by Scott M. on 2/1/2016 as part of a GitHub housekeeping clean-up effort. the issue will be closed.
