### ISSUE TITLE
Non-Modification Response Form - Updates to Layout & Text Labels

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#147]
**Tad has requested a few updates to the layout of the Non-Modification Approval Response form.**
Please find the list of updates below.

1. **Update the text of the title/heading on the page to "QA Concurrence"**

2. **Update the text of the label above the Approval dropdown to "QA Response"**

![image](https://cloud.githubusercontent.com/assets/4098544/6597676/9b68d454-c7d4-11e4-915a-b7c85b4bb06d.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
this issue was initially implemented and tested in spring of 2015 and was successfully validated again by Scott M. on 2/1/2016 as part of a GitHub housekeeping clean-up effort. the issue will be closed.
