### ISSUE TITLE
QA Toolkit - Project Details PDF Report - Update Text of "Approvals (Non-Mods)" Heading

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#148]
Within the Project Details PDF Report, **please update the text of the "Approvals (Non-Mods)" Heading to "QA Concurrence"**
![image](https://cloud.githubusercontent.com/assets/4098544/6597913/414a3c7c-c7d6-11e4-8b12-c853a2e52872.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validated successfully in KCI DEV - updated to Ready for Staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
