### ISSUE TITLE
QA Toolkit - Admin Menu: User Edit Screen - Spelling Correction: "Modifications & Approvals"

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#149]
Please correct the spelling mistake highlighted below. The correct spelling should be "Project Modifications & Approvals"

![image](https://cloud.githubusercontent.com/assets/4098544/6599166/b1f97c3c-c7de-11e4-852d-3485ac082115.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validated successfully in KCI DEV - updated to Ready for Staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
