### ISSUE TITLE
Non-Modification Request & Response Forms - Enable Approval Dropdown for Specific System Roles

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#150]
Please **update the _Non-Modification Request Form_ and _Non-Modification Response Form_ so that the Approval Dropdown is enabled for the system roles listed below** 

**Disable the dropdown for all other system role user profiles that are not listed.**

**Enabled:**
1. ESC Manager
2. Project Manager
3. Inspector

**Disabled:**
1. Reviewer
2. Project Engineer
3. Contractor
4. Power Reviewer

![image](https://cloud.githubusercontent.com/assets/4098544/6599814/45559558-c7e2-11e4-8e87-1df9b6a2e5cb.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
related to #155

**Comment by slmessier** [comment]
Please add Project manager to the list of system roles having permission to make this change:
3 roles in total have capability:
1. ESC Manager
2. Inspector
3. Project Manager

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
Drop down remains disabled for Project Manager System role. Please enable foe Project Manager (as well as ESC Manager and Inspector)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validated successfully in KCI DEV - updated to Ready for Staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
