### ISSUE TITLE
Inspections Tab - Update Security Settings for Contractor & Project Engineer Roles - Display Assigned Projects Only

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#151]
Please **update the system logic for the Inspection Tab so that the system displays Inspections records exclusively for Projects assigned to the active user**

**Apply exclusively to the following System Roles: 
1. Contractor
2. Project Engineer**

Email from Tad below:
![image](https://cloud.githubusercontent.com/assets/4098544/6604013/ea06d364-c7fb-11e4-998e-5460468a806d.png)

**Comment by kanglu666** [comment]
works correctly for me, please double check

**Comment by slmessier** [comment]
*this issue has been identified and confirmed as an intended feature of the system, and not an issue (see below). As such, it will be closed.**

From: Tad Daniel [mailto:tdaniel@sha.state.md.us] 
Sent: Thursday, March 12, 2015 6:30 AM
To: Scott Messier
Cc: Heidi Hammel; Lu Kang
Subject: RE: found an issue with user roles

I'll be damned, you are right.
 
I have never noticed this before because up until now the user base was limited.  Everything is OK as is....
 
Its not a bug, Its a feature.....   ;-)
 
Thanks
 
Tad Daniel
 
Environmental Programs Division
Regional Environmental Coordinator Team Leader
410-365-0164
 
________________________________________
From: Scott Messier [Scott.Messier@kci.com]
Sent: Wednesday, March 11, 2015 3:52 PM
To: Tad Daniel
Cc: Heidi Hammel; Lu Kang
Subject: RE: found an issue with user roles
I think that what you are seeing is occurring from a whole slew of CLOSED projects that remain assigned to each user. Please check the checkbox to display closed projects (green box below) and see if the listed inspections match up with the results you expect:
 ![image](https://cloud.githubusercontent.com/assets/4098544/6617289/99a5d8d8-c88d-11e4-83a6-c1ffa73c22d4.png)
