### ISSUE TITLE
QA Toolkit - Modification Request - Email Notification Template

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#154]
**Update the visual layout of the system email notifications to match the designed layout of the wireframes**
1. Implement the usage of Bold & regular fonts according to the original design
2. Implement the spacing and location according to the original design

## Wireframe specifications
![image](https://cloud.githubusercontent.com/assets/4098544/6869988/8d6a08e4-d46f-11e4-881e-6396dad7cdf9.png)

## Existing system notifications
![image](https://cloud.githubusercontent.com/assets/4098544/6870035/be1ce6d2-d46f-11e4-989d-62c6123df62a.png)

**Comment by kanglu666** [comment]
done at KCI, only can be tested when push to staging
![email_temp](https://cloud.githubusercontent.com/assets/6352480/6888758/8fe24702-d655-11e4-948c-6eace4f7259e.JPG)

**Comment by slmessier** [comment]
Please correct the 2 spelling mistakes within the graphic below:
![untitled_clipping_033015_083316_am](https://cloud.githubusercontent.com/assets/4098544/6896290/c8b4f806-d6b7-11e4-9ff6-4b3b5a82c7ec.jpg)

**Comment by kanglu666** [comment]
done, ready for pushing to sha staging

**Comment by magregory** [comment]
Template is updated to specifications however the text "by Package Approver:" is not in the template. Instead it just says " by: "

**Comment by slmessier** [comment]
these updates have been confirmed in KCI DEV and will be marked for push to STAGING targeting 2/4/16 for release.

**Comment by magregory** [comment]
Update template to include text "by Package Approver:" to template to show users permissions. 

![image](https://cloud.githubusercontent.com/assets/16670108/12818125/7a1418ce-cb23-11e5-9245-8d0e902e35f4.png)

**Comment by vijme** [comment]
Done. Please check

**Comment by vijme** [comment]
tested in staging

**Comment by Tad-Daniel** [comment]
Working well

**Comment by Tad-Daniel** [comment]
Issue complete
