### ISSUE TITLE
QA3 PDF Report - Revisions to Layout

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#156]
Please implement the following revisions to the QA3 PDF form:
1. Add “OOC62 / “ text to top left heading branding
2. Increase text limit of “Nature of Revisions” field & “Reasons for Revision” field
3. Remove bounding box from Nature of Revision field
![image](https://cloud.githubusercontent.com/assets/4098544/6874541/7879563c-d48e-11e4-8067-1fd70f4e2925.png)

**Comment by kanglu666** [comment]
done at KCI

**Comment by slmessier** [comment]
The text within the _Nature of Revision_ and _Reason for Revision_ boxes is still being cutoff.

Please reconcile the character limit of the PDF with the character limit of the UI. If necessary, implement a method of control in the user interface (Modification Request Form) to prevent or indicate that the character length threshold has been exceeded.

**Comment by slmessier** [comment]
related to issue #158

**Comment by kanglu666** [comment]
form updated,both two text area now have maximal place in the first page.

**Comment by slmessier** [comment]
Per Tad's request - the date valuye that is included in the top left of the PDF form should be hard coded as "03/20/2015" which is the date the form was approved.

![image](https://cloud.githubusercontent.com/assets/4098544/6929665/a8cb4130-d7ca-11e4-9458-56ee5abac5ec.png)

**Comment by kanglu666** [comment]
what do you mean "hard coded as the date the form was approved"?

**Comment by slmessier** [comment]
instead of using the current system date, pleas use the string "03/20/2015"

**Comment by kanglu666** [comment]
where the string "03/20/2015" come from?

**Comment by slmessier** [comment]
it should be hard coded as a string

**Comment by kanglu666** [comment]
updated at both KCI dev and SHA staging, please test

**Comment by slmessier** [comment]
validated successfully in KCI DEV - updated to Ready for Staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
