### ISSUE TITLE
Modification Request Form - Update Button Text Label: "Submit" --> "Save/Submit"

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#157]
Please update the text label of the Submit button on the Modification Request Form by changing the text from "Submit" to "Save/Submit"

![image](https://cloud.githubusercontent.com/assets/4098544/6874681/ad1edadc-d48f-11e4-8c1f-b59f899d4c6f.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validated in KCI DEV - updated to Ready for Staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
