### ISSUE TITLE
Modification Request Form - Increase or Implement Error control for the character length of “Nature of Revision” & “Reason for Revisions” text input fields

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#158]
**Please investigate the character limit** associated with these two fields in the system by checking on the limitations existing within the UI and the database. **Depending on the configuration of the existing constraints, please either increase the character limit, or implement a method of error control in the UI to indicate to the user that the limit has been exceeded**.

![image](https://cloud.githubusercontent.com/assets/4098544/6874829/abdbd76e-d490-11e4-885b-4d8463cdef65.png)

**Comment by slmessier** [comment]
related to issue #156

**Comment by slmessier** [comment]
Please implement a message that completes the following workflow:
1. user enters text with 750+ characters into the _Nature of Revision_ input field
2. user enters text with 750+ characters into the _Reason for Revision_ input field
3. user clicks _Save/Submit_
4. system displays new pop-up message  - **"Nature of / Reason for Revision text exceeds 750 characters. The associated text on the QA-3 form will be truncated"**. The message includes 2 buttons - _Continue_ & _Revise_.
5. If the user clicks _Continue_ the system saves the pending edits.
6. If the user clicks _Revise_ the system returns to the Request form without saving the edits.
![image](https://cloud.githubusercontent.com/assets/4098544/6904253/90296b80-d6ed-11e4-84d8-80ddda6ec3e7.png)

![image](https://cloud.githubusercontent.com/assets/4098544/6904477/02ebcd42-d6ef-11e4-81e0-e643fa0b4fbe.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
this enhancement has been implemented using an alert message in place of the pop-up message that was initially designed due to complexity of development.
![image](https://cloud.githubusercontent.com/assets/4098544/6908918/1a7700ba-d70f-11e4-994e-b65f0d3c094a.png)

**Comment by slmessier** [comment]
validated successfully in KCI DEV - updated to Ready for Staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
