### ISSUE TITLE
QA Toolkit - Remove Margin Space on Left/Right of all Pages

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#159]
Remove or Reduce gray margin area on left and right of page - shown in blue in the graphic below
![image](https://cloud.githubusercontent.com/assets/4098544/6874958/a6806fa4-d491-11e4-8b65-b397b76de56a.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validated successfully in KCI DEV - updated to Ready for Staging

**Comment by slmessier** [comment]
On the Modification Request Form  when the project description text extends onto more than 1 line, the system modifies the display of the entire form in a way that causes the vertical scroll bar to obstruct a portion of the user input fields (see graphic below).

**Please update the dynamic display so that user input fields are not obstructed under this condition.**

![image](https://cloud.githubusercontent.com/assets/4098544/6943457/2ef7b342-d85c-11e4-9031-ca14af9f34ee.png)

**Comment by kanglu666** [comment]
done at KCI

**Comment by slmessier** [comment]
validated successfully at KCI DEV - updated to Ready for Staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
