### ISSUE TITLE
Modification Request Form - REC/QA Value Erroneously Populated

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#162]
The system currently displays the REC/QA erroneously after the user clicks on submit on the Modification Request Form.

**Steps to Replicate Issue:**
1. Begin a New Modification Request
2. Complete the Contractor, SHA Project Engineer, & REC/QA authentication workflow **using 3 distinct user accounts.** ![image](https://cloud.githubusercontent.com/assets/4098544/6875946/8405ba58-d499-11e4-8d17-c5813c881392.png)
3. Click the submit button to save
4. the system will erroneously display the value within the REC/QA field (will display the SHA Project Engineer username) ![image](https://cloud.githubusercontent.com/assets/4098544/6875933/72058af4-d499-11e4-85dd-09343381e616.png)

**Comment by kanglu666** [comment]
fixed at KCI

**Comment by slmessier** [comment]
validated successfully in KCI Dev - updated to Ready for Staging

**Comment by slmessier** [comment]
validated successfully in Staging - updated to Ready for Production

**Comment by Tad-Daniel** [comment]
issue resolved
