### ISSUE TITLE
QA Toolkit - Relocate Templates to behind the Admin Menu

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#163]
**Note: this issue is lower priority than QA1 & QA2 Forms development**
Move Print Templates tab to admin menu

![image](https://cloud.githubusercontent.com/assets/4098544/6876040/19281b80-d49a-11e4-9533-f7e6c0bbe22c.png)

**Comment by kanglu666** [comment]
done at KCI, ready for testing

**Comment by slmessier** [comment]
this issue was initially implemented and tested in summer of 2015 and was successfully validated again by Scott M. on 2/1/2016 as part of a GitHub housekeeping clean-up effort. the issue will be closed.
