### ISSUE TITLE
QA Toolkit - Redesign the Mods (Primary) Tab

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#164]
**Note: this issue is lower priority than QA1 & QA2 Forms development**

Implement the following updates to the Mods (Primary) Tab
1. Viewable & Accessible to the ESC Manager system role only
2. Remove icons currently on the right side and replace with an icon to hyperlink that links to the associated project
3. Remove the “New Request” button completely
4. Columns within the grid should be: Package status, submission date, approval status, approved date, & “approval time”. “Approval time is calculated by <Approval date> – <package submission date> in days
![image](https://cloud.githubusercontent.com/assets/4098544/6876128/bfadfa1a-d49a-11e4-9bd0-9654371a47ff.png)

**Comment by kanglu666** [comment]
done at KCI ready for testing

**Comment by slmessier** [comment]
Please enable the MODS tab for the following (2) system role profiles:
- ESC Manager
- Project Manager

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validated successfully in KCI Dev - updated to Ready for STAGING

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
