### ISSUE TITLE
QA Concurrence Tab - Email Notifications Not functional

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#165]
Please **implement the email notifications for the QA Concurrence tab** and associated workflow.

**For QA Concurrence, there are 4 conditions that when met should function as triggers** for the system to send email notifications:

1. **Original Request Form - user checks notification recipients** ![image](https://cloud.githubusercontent.com/assets/4098544/6942241/402273d0-d854-11e4-8922-c76e3dad980e.png)

2. **Response form - user checks notification recipients** ![image](https://cloud.githubusercontent.com/assets/4098544/6942246/4788e730-d854-11e4-8a1f-e5d877ecb602.png)

 3. **Admin Subscriptions – All requests & responses user subscription** ![image](https://cloud.githubusercontent.com/assets/4098544/6942248/500324b6-d854-11e4-9445-3a0b6157fe5b.png)

 4. **Admin Subscriptions – Approvals only user subscription** ![image](https://cloud.githubusercontent.com/assets/4098544/6942251/55ace71c-d854-11e4-944f-0e16bf33eb59.png)

**Comment by kanglu666** [comment]
please provide the email template for the QA Concurrence notification.

**Comment by slmessier** [comment]
Please find the mockup below:
![qa_concurrence_notification](https://cloud.githubusercontent.com/assets/4098544/6945913/f634fefc-d86a-11e4-82d4-59918b235865.png)

**Comment by slmessier** [comment]
Please include the creator of the original request in the list of recipients

**Comment by kanglu666** [comment]
done at SHA staging, ready for testing

**Comment by magregory** [comment]
Email notification is implemented and successfully sends notification for QA concurrence request.

**Comment by slmessier** [comment]
these updates have been confirmed in KCI DEV and will be marked for push to STAGING targeting 2/4/16 for release.

**Comment by Tad-Daniel** [comment]
Appears to be working correctly.

**Comment by Tad-Daniel** [comment]
Appears to function correctly, ready for production.

**Comment by Tad-Daniel** [comment]
Implemented in production and working.
