### ISSUE TITLE
QA Toolkit - STAGING Environment only - Package Approval/Submission functionality not complete

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#166]
There is an issue *specific to the STAGING* environment with the functionalies and capabilties associated with Rec/QA represtatives & Package Approvers.

These issues do not appear in PRODUCTION or DEVELOPMENT and are likely exclusive to the STAGING environment.

Please see a description of the reported issues below:
![image](https://cloud.githubusercontent.com/assets/4098544/6943210/743f8602-d85a-11e4-9e5e-40f943a820b4.png)

![image](https://cloud.githubusercontent.com/assets/4098544/6943183/4d376926-d85a-11e4-9baf-fa9d24f7e055.png)

**Comment by kanglu666** [comment]
fixed, Package Approved has been renamed to Package Submitted

**Comment by slmessier** [comment]
this issue seems to become alleviated when the Package Approver user permissions are "reset" by using the admin menu to un-check, the re-check the appropriate checkboxes.

if the issue recurs for future deployments, development team will need to come up with a strategy to account for resolving it.

**Comment by slmessier** [comment]
From: Tad Daniel [mailto:tdaniel@sha.state.md.us] 
Sent: Wednesday, April 01, 2015 11:52 AM
To: Scott Messier
Cc: Heidi Hammel; Cheryl Jordon (SHA)
Subject: RE: New Release available in Staging

Looks good
Everything seems to be working correct now.

 
From: Scott Messier [mailto:Scott.Messier@kci.com] 
Sent: Wednesday, April 01, 2015 11:34 AM
To: Tad Daniel
Cc: Heidi Hammel; Cheryl Jordon (SHA)
Subject: RE: New Release available in Staging

Hi Tad,
We’ve updated STAGING to address the REC/QA field and related issues. Could you re-test and confirm?
Thank you!

**Comment by slmessier** [comment]
this issue seems to become alleviated when the Package Approver user permissions are "reset" by using the admin menu to un-check, the re-check the appropriate checkboxes.

if the issue recurs for future deployments, development team will need to come up with a strategy to account for resolving it.

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
