### ISSUE TITLE
QA Toolkit - QA3 PDF Report - Update "Approved By" Label Text & Associated Layout

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#169]
# Requested Fix
**Update the QA3 PDF Template to:
1. update the text label for _"Approved by:"_ to _"by:"_
2. Add space characters after the _project number value_** to provide a visual spacing element to more adequately separate the project number from the _"by:"_ label.

## Original Email from Tad
From: Tad Daniel [mailto:tdaniel@sha.state.md.us] 
Sent: Wednesday, April 08, 2015 1:44 PM
To: Heidi Hammel; Scott Messier
Subject: RE: Modification notification email

I do see one bit of text to adjust,  remove the words “package approver” so that it just reads “by: ……….” And add a few spaces after the project number to show some seperation.
![image](https://cloud.githubusercontent.com/assets/4098544/7069759/ace17048-dea8-11e4-9fd9-33712fa8066c.png)

**Comment by slmessier** [comment]
validated in STAGING (validation in KCI DEV not applicable due to notifications not existing within that environment) - **updated to "Ready for Production"**

**Comment by slmessier** [comment]
Tad - I believe this issue has been resolved. Please confirm and close if applicable.

**Comment by Tad-Daniel** [comment]
Issue fixed....
