### ISSUE TITLE
QA Toolkit - New Approval Request Status Value: "Request Withdrawn"

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#171]
Please add the following system logic at Tad's request:
**1. add a new Request Status Value: as "Request Withdrawn"
2. add a system trigger to automatically update the Request Status = "Request Withdrawn" when the Package Status = "Package Withdrawn"
3. Update the QA3 PDF form to display "Request Withdrawn" when the Request Status = "Request Withdrawn"**

**Comment by slmessier** [comment]
The following items related to this request may require clarification from Tad:
1. Is the solution described above for QA3 PDF sufficient? 
2. Confirm that packages (package status) will never be approved for submission after being withdrawn?

**Comment by slmessier** [comment]
Tad has provided confirmation that the assumptions above (1 and 2) are valid. (email sent to scott on 4/17/2015)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validated successfully in KCI DEV - updated to Ready for Staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
