### ISSUE TITLE
QA1 Inspection Form PDF - Update "Contract No" Label

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#175]
Page 1 - Update “Contract No.:” label – currently says _Contract:_ please update to **_Contract No.:_**
![image](https://cloud.githubusercontent.com/assets/4098544/7209791/fd9d1c40-e519-11e4-9d70-d9cda6ab0305.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validated in KCI Dev - updated to Ready for Staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
