### ISSUE TITLE
QA1 Inspection Form PDF - Update "**Non-Compliance" Label

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#176]
Page 1 - Update “ ** Non-Compliance” label – currently says _Non-Compliance_ update to **_“ ** Non-Compliance”_**

![image](https://cloud.githubusercontent.com/assets/4098544/7209878/b75b0dc2-e51a-11e4-9a09-e6dcd59c9653.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validated in KCI Dev - updated to Ready for Staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
