### ISSUE TITLE
QA1 Inspection Form PDF - Update 3 Grade Labels

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#177]
Page 1 - Update  3 grade labels – currently says “C” “D” “F” update to “ ** C” “ ** D” “ ** F”

![image](https://cloud.githubusercontent.com/assets/4098544/7209893/ebb89c7e-e51a-11e4-855c-88d931164a92.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validated in KCI Dev - updated to Ready for Staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
