### ISSUE TITLE
QA1 Inspection Form PDF - All Sections Missing Column Values

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#178]
All sections (1 through 6) - Point / Selection values missing for the following 5 columns:
1. “Point  Value”
2. “Y”
3. “N”
4. “Pts Awarded”
5. “NA”

![image](https://cloud.githubusercontent.com/assets/4098544/7209911/284e177c-e51b-11e4-8191-b1b117cb69ff.png)

**Comment by kanglu666** [comment]
done at KCI, ready for testing

**Comment by slmessier** [comment]
validated in KCI Dev - updated to Ready for Staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
