### ISSUE TITLE
Modification Response Form - Increase Response Text Character Limit to 500

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#181]
Tad has requested that the _**Response Text**_ field be increased to 500 characters on the _Modification Response Page_.
![image](https://cloud.githubusercontent.com/assets/4098544/7420453/96cf27de-ef4a-11e4-89cd-4845f00661b0.png)

**Comment by kanglu666** [comment]
DONE

**Comment by slmessier** [comment]
validated successfully in KCI Dev - updated to Ready for Staging

**Comment by Tad-Daniel** [comment]
Item completed
