### ISSUE TITLE
QA1 Inspection Form UI - Update Label Superintendent

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#182]
Please remove the _ESC_ characters from the _ESC Superintendent_ label so that the updated label is _Superintendent_
![image](https://cloud.githubusercontent.com/assets/4098544/7420851/f2c504fc-ef4d-11e4-8a62-4bbcb71833d3.png)

**Comment by kanglu666** [comment]
it will effect all the template, so i will just leave it as is.

**Comment by slmessier** [comment]
Tad has specified that it is OK to proceed with this update even if it affects the template. Please update - thank you.

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validated successfully in KCI Dev - updated to Ready for STAGING

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
