### ISSUE TITLE
QA1 Inspection Form UI - Update Grade Table - Remove Points Row and Bonus Row

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#185]
**Please remove points row and Bonus row leaving only the Grade Heading, Grade, and Rating:**

**Current Grade Table**:
![image](https://cloud.githubusercontent.com/assets/4098544/7421396/0a613708-ef52-11e4-962d-ee3005649c5d.png)

**Updated Grade Table**:
![image](https://cloud.githubusercontent.com/assets/4098544/7421381/f7105c4c-ef51-11e4-8270-b067b3ba3c0d.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validated successfully in KCI Dev - updated to Ready for STAGING

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
