### ISSUE TITLE
QA1 Inspection Form PDF - Update Label within Point Math Totals for Section 1-4

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#186]
Please update the label shown in the graphic below to display the text: _**"(Section 1-4 Total) x 80%"**_

![image](https://cloud.githubusercontent.com/assets/4098544/7421503/d9f89222-ef52-11e4-9e4b-ffe60cfda5b4.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validated successfully in KCI Dev - updated to Ready for STAGING

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
