### ISSUE TITLE
QA1 Inspection Form PDF - Lower the Vertical Position on Page of "Received By" Signature

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#187]
The Received By signature cuts off the line immediately above. Please lower the Received by Signature Line and the page Footer lower on the page

Existing System:
![image](https://cloud.githubusercontent.com/assets/4098544/7421601/17d495c2-ef54-11e4-9513-842ea09f521a.png)

Updated System:
![image](https://cloud.githubusercontent.com/assets/4098544/7421618/2e5353c4-ef54-11e4-95ad-577d17140cd6.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validated successfully in KCI Dev - updated to Ready for STAGING

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
