### ISSUE TITLE
QA1 Inspection Form PDF - Adjust Date Label & Date Values for "ENV.Coordinator" & "Contractor" Signatures

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#188]
Please adjust the report layout related to the following signature values:

1. Align Date labels to be in vertically in line
2. Move Date values left so that they appear adjacent to the date labels
3. Align Date Values to be vertically in line

![image](https://cloud.githubusercontent.com/assets/4098544/7421798/bb63ce28-ef55-11e4-9b9b-c3f5d9da51f2.png)

**Comment by kanglu666** [comment]
done at KCI

**Comment by slmessier** [comment]
validated successfully in KCI Dev - updated to Ready for STAGING

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
