### ISSUE TITLE
QA2 Inspection Form - (2) Spelling Corrections: UI & PDF

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#189]
The QA2 inspection form needs 2 revisions to spelling on the labels that appear on both the _**UI and PDF**_:

1. Question 4 - Correct **"As-Built _Paln_"** to **"As-Built _Plan_"**
1. Question 11 - Correct **"their _fianl_ inspection"** to **"their _final_ inspection"**

![image](https://cloud.githubusercontent.com/assets/4098544/7727647/1ad86b5c-fed8-11e4-9d31-e0c63c7e3895.png)

**Comment by kanglu666** [comment]
updated at KCi, ready for testing.

**Comment by slmessier** [comment]
validated in KCI DEV - updated to Ready for Staging.

**Comment by Tad-Daniel** [comment]
This item is complete
