### ISSUE TITLE
QA Toolkit - Forgot Password functionality not working

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#191]
•	Forgot your password system not working correctly. – LOW PRIORITY

**Comment by kanglu666** [comment]
just tested, the password reset function is working correctly.
currently  the login and Email (for reset password) are case sensitive.
i will update to make them not case sensitive.

**Comment by Tad-Daniel** [comment]
Tested this today in production and it appears to be working fine.
