### ISSUE TITLE
QA Toolkit - Update System Navigation to Display Mods Menu

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#192]
•	When pressing the “Close” button you will be taken back to the Mods sub-menu. – medium

**Comment by kanglu666** [comment]
updated

**Comment by vijme** [comment]
Updated in KCI dev. Please test

**Comment by magregory** [comment]
Tested. Correct navigation is in place when closing mods sub-menu.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by Tad-Daniel** [comment]
Issue complete
