### ISSUE TITLE
QA Toolkit - QA-3 Input Form - Update Logic for Rec/QA signature

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#195]
The REC blank on the OOC62/QA-3 form will be automatically filled in when Package Approver move a package to review. (This will remove a duplication of effort on our part).

**Comment by slmessier** [comment]
Tad has requested this update at this time. Please begin development using details below:
1. On modification response form, user updates Package Status dropdown to _Package Submitted_
2. System prompts user to Sign / Authenticate
3. User (with Package Approver permissions) Signs/ Authenticates by entering user credentials
4. System accepts valid user credentials
5. User clicks Save button to save pending updates
6. **NEW - System automatically populates the REC/QA value for the active modification record using the user account that was successfully authenticated after "signing" for Package status = _Package Submitted_**

**Comment by vijme** [comment]
Based on discussion with Tad on 2/8/16, the REC/QA button needs to be removed from QA-3 form, and should be auto-populated based on the user account that was authenticated for "Package Submitted" sign.

**Comment by vijme** [comment]
Done. Please check

**Comment by vijme** [comment]
Tested in staging

**Comment by Tad-Daniel** [comment]
Working well. Thanks

**Comment by Tad-Daniel** [comment]
In production when atempting to submit a modification request the system returns an error"failed to save response" this was noted ob BA366 mod 14 when submiting to the QAProgram for review.  This is a priority to look into as it effects production.

**Comment by Tad-Daniel** [comment]
issue complete
