### ISSUE TITLE
QA Toolkit - Mods SubMenu - Add Modification Number to list

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#196]
Modification number included in the mod submenu list. - high
![image](https://cloud.githubusercontent.com/assets/4098544/8137437/6d32db26-1111-11e5-83b6-ffbcb0cc8fc2.png)

**Comment by kanglu666** [comment]
updated

**Comment by slmessier** [comment]
this issue was initially implemented and tested in summer of 2015 and was successfully validated again by Scott M. on 2/1/2016 as part of a GitHub housekeeping clean-up effort. the issue will be closed.
