### ISSUE TITLE
QA Toolkit - QA-3 PDF Report - Remove Pages 3 and 4

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#197]
Update OOC62/QA-3 PDF (remove page 3 and 4) - high

**Comment by kanglu666** [comment]
updated at KCI

**Comment by slmessier** [comment]
this issue was initially implemented and tested in summer of 2015 and was successfully validated again by Scott M. on 2/1/2016 as part of a GitHub housekeeping clean-up effort. the issue will be closed.
