### ISSUE TITLE
QA Toolkit - Project Summary PDF Report - Incorrect Modification & Concurrence Info

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#198]
•	Project summary PDF not correct related to modifications. - high

**Comment by kanglu666** [comment]
updated

**Comment by slmessier** [comment]
this issue was initially implemented and tested in summer of 2015 and was successfully validated again by Scott M. on 2/1/2016 as part of a GitHub housekeeping clean-up effort. the issue will be closed.
