### ISSUE TITLE
QA Toolkit - PDF Report of Mods Tab Grid

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#199]
Print out (PDF) of modification summary. – medium
![image](https://cloud.githubusercontent.com/assets/4098544/8137547/3746a53c-1112-11e5-9734-ede2cecea4c7.png)

**Comment by kanglu666** [comment]
printing function added

**Comment by slmessier** [comment]
this issue was initially implemented and tested in summer of 2015 and was successfully validated again by Scott M. on 2/1/2016 as part of a GitHub housekeeping clean-up effort. the issue will be closed.
