### ISSUE TITLE
QA Toolkit - Update System Scrolling

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#201]
•	Can the top menus and banner be stationary while the rest of the page scrolls up and down? (Like framesets) – LOW PRIORITY

**Comment by kanglu666** [comment]
updated at KCI

**Comment by slmessier** [comment]
The screen shot below shows what happens when there is a second row of menu items.  The second row obstructs the page heading / title on the page so that the title cannot be seen (circled in red)  

**Please add an additional line(s) at the top of the pages or a buffer of some 
sort to ensure the page titles are not obstructed and can be seen by all.**

![image](https://cloud.githubusercontent.com/assets/4098544/8232068/dde2d2e4-159a-11e5-8d0e-b7882cdfd1b8.png)

**Comment by kanglu666** [comment]
updated

**Comment by slmessier** [comment]
this issue was initially implemented and tested in summer of 2015 and was successfully validated again by Scott M. on 2/1/2016 as part of a GitHub housekeeping clean-up effort. the issue will be closed.
