### ISSUE TITLE
QA Toolkit - Mods Tab/Grid - Remove "Request User" column

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#202]
•	Remove “request user” column from MODS grid. - high

**Comment by kanglu666** [comment]
updated at KCI

**Comment by slmessier** [comment]
this issue was initially implemented and tested in summer of 2015 and was successfully validated again by Scott M. on 2/1/2016 as part of a GitHub housekeeping clean-up effort. the issue will be closed.
