### ISSUE TITLE
QA Toolkit - QA3 & Mod Response Form - Add Character Limit text

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#204]
Add instructive notes on QA-3 input page and at form fields. - high
1.	On the QA3 input form, Modification response page and the QA Concurrence page add “(500 character limit)” above each text input box (nature of revision, reason for revision, response text field).
2.	Character limit warning

**Comment by kanglu666** [comment]
updated at KCI

**Comment by slmessier** [comment]
Please ensure that the character limit is consistently 500 characters for each instance.

**Comment by vijme** [comment]
Fixed at KCI Dev. please test

**Comment by Tad-Daniel** [comment]
looks good

**Comment by Tad-Daniel** [comment]
Issue complete
