### ISSUE TITLE
QA Toolkit - Update Text & Formatting of Inspection Report Email Notification

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#205]
Adjust language and formatting report notification email.
1.Update Report notification email with items below. - high
-Add line breaks to mimic actual report
-Change “Notes:” to “General inspection comments”
-Add “Line item comments” after the general notes.
![image](https://cloud.githubusercontent.com/assets/4098544/8137821/1311af70-1114-11e5-8588-90b5fa4480c7.png)

**Comment by kanglu666** [comment]
updated at KCI, only can be test once push to SHA staging.

**Comment by magregory** [comment]
This notification template was tested and is up to date with specifications.

**Comment by slmessier** [comment]
these updates have been confirmed in KCI DEV and will be marked for push to STAGING targeting 2/4/16 for release.

**Comment by Tad-Daniel** [comment]
I edited the report from SO438ZM2 dated 6-5-15 to test the notification system and received the "Failed to send notifications pop-up"

![failed](https://cloud.githubusercontent.com/assets/7913678/12919646/25960f2a-cf13-11e5-9cd8-8853f7afe957.png)

I tried it for AT376 dated 2-9-2016 and the system says the notifications were sent but I did not receive an email,  possibly just a delay at the mail server

**Comment by magregory** [comment]
Viji, please investigate whether the inspection report notifications are being sent for the projects listed.

**Comment by Tad-Daniel** [comment]
Update:  The two inspection reports that were sent got caught by SHA's spam system.
The formating still does not have the proper line, paragraph breaks or underlined titles.

**Comment by magregory** [comment]
Tad - Thanks for the update. Can you confirm if there is still an error with notifications for report associated with SO438ZM2?

Viji - Please update the template to match line formatting in template screenshot.

**Comment by Tad-Daniel** [comment]
Still getting the "error: failed to send notification"

**Comment by vijme** [comment]
Email Template updated. Failed Notifications are now a separate GitHub Issue #229

**Comment by vijme** [comment]
Tested in staging.

**Comment by Tad-Daniel** [comment]
It appears to be working bu I believe the SHA spam system is catching the notification.

Could you attach a screen-shot of the notification email for me.

**Comment by vijme** [comment]
![capture](https://cloud.githubusercontent.com/assets/6668314/13013413/652b91c0-d17d-11e5-98cf-6a33d808e808.PNG)

**Comment by Tad-Daniel** [comment]
Yep,  looks good..

**Comment by Tad-Daniel** [comment]
Issue complete
