### ISSUE TITLE
QA Toolkit - Update Text & Formatting of New User Account Email Notification

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#206]
Update the email notification that the system issues when  a new user account has been created. Reference the graphic below:

![image](https://cloud.githubusercontent.com/assets/4098544/8137841/35f10da6-1114-11e5-8097-e7f379e2bf6c.png)

**Comment by kanglu666** [comment]
updated at KCi, only can be test at SHA staging or prod after push.

**Comment by magregory** [comment]
The new user notification works correctly and matches format in screenshot.

**Comment by slmessier** [comment]
these updates have been confirmed in KCI DEV and will be marked for push to STAGING targeting 2/4/16 for release.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by Tad-Daniel** [comment]
Issue Complete
