### ISSUE TITLE
QA Toolkit - QA2 Inspection Form - Add Print Button & PDF Function

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#207]
•	Include a print button on the page to print the PDF.  Just like the OOC61/QA1 - high

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
this issue was initially implemented and tested in summer of 2015 and was successfully validated again by Scott M. on 2/1/2016 as part of a GitHub housekeeping clean-up effort. the issue will be closed.
