### ISSUE TITLE
QA Toolkit - QA2 Inspection Form - Previous Button to View Previous Inspection

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#208]
•	Include a previous inspection button on the page to view the PDF of the previous QA2 report.   Just like the OOC61/QA1 - high

**Comment by kanglu666** [comment]
print and print previous buttons and functions have been added.

**Comment by slmessier** [comment]
this issue was initially implemented and tested in summer of 2015 and was successfully validated again by Scott M. on 2/1/2016 as part of a GitHub housekeeping clean-up effort. the issue will be closed.
