### ISSUE TITLE
QA Toolkit - QA2 PDF Form - Update Aesthetic Layout - Remove Border

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#209]
•	Remove border around questions and line items comments on page two of the PDF- high

**Comment by kanglu666** [comment]
fixed at KCI

**Comment by slmessier** [comment]
this issue was initially implemented and tested in summer of 2015 and was successfully validated again by Scott M. on 2/1/2016 as part of a GitHub housekeeping clean-up effort. the issue will be closed.
