### ISSUE TITLE
QA Toolkit - QA2 PDF Form - Link Functionality to System Roles/Profiles

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#211]
This QA2 functionality should be available to the following system roles:
-	Inspector (full edit capabilities for assigned projects)
-	ESC Manager (already there and working correctly)
-	Project Manager (read  only)
-	Project engineer (read only)

**Comment by slmessier** [comment]
validated in KCI DEV - Ready for push to Staging/Prod

**Comment by slmessier** [comment]
**Update QA2 functionality specifically for system role = Inspector (see email below)**

-----Original Message-----
From: Tad Daniel [mailto:tdaniel@sha.state.md.us] 
Sent: Friday, June 26, 2015 11:43 AM
To: Scott Messier
Cc: Heidi Hammel
Subject: RE: first issue notice by the update.

I just checked the different roles and it looks good.   Go ahead and push to production tonight.

**One adjustment that is needed is that the QA inspectors should be limited to only editing their own reports and not reports that others have written.  Reports others have written should be read only.**  Don't let this minor tweak stop the push to production though.

Thanks


Tad Daniel

**Comment by Tad-Daniel** [comment]
Implemented in production and working.
