### ISSUE TITLE
QA2 Inspection Form - Expand Text Input Field for Line Item Comments

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#212]
- Expand text input box for line items comments to 3 lines.

**Comment by slmessier** [comment]
Please update the form to restrict the user from entering text characters beyond 3 lines.

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
During the entry worfklow when the user is enters the line item comments, **can the text input field be updated to not allow the user to enter additional characters?**

![image](https://cloud.githubusercontent.com/assets/4098544/8579951/b158b7f2-2585-11e5-9744-610376ec5ff8.png)

**Comment by kanglu666** [comment]
only can set the length of characters, not the lines.
right now i set it to 255.

**Comment by slmessier** [comment]
A 255 character limit will provide the expected functionality.

However, when testing the 255 limit, **I was able to copy/paste 255+ characters**. (works as expected when typing, but I'm allowed to enter more than 255 if i copy and past:

Sample text below:
characterscharacterscharacterscharacterscharacterscharacterscharacterscharacterscharacterscharacterscharacterscharacterscharacterscharacterscharacterscharacterscharacterscharacterscharacterscharacterscharacterscharacterscharacterscharacterscharacterschara______beyond 255

**Comment by kanglu666** [comment]
that's a framework issue, i can limit the type, but now way to control the copy/paste.
But, even user copy/paste more 255 characters, the database and UI will only save 255.

**Comment by slmessier** [comment]
Since the framework will not allow control over the number of characters in copied/pasted text, it will be sufficient if the database saves only 255 characters. 

However, **the system DOES save characters beyond 255 based on the PDF output below. Please update the system so that only 255 characters are saved.** the goal is to limit the number of saved characters to 255 so that the total text does not continue over 3 lines on the output PDF.

(from QA2 inspection added on 7/14 to project # _QA2_Test_)
![image](https://cloud.githubusercontent.com/assets/4098544/8681195/1817dfe2-2a34-11e5-8364-d5f73a8f7acd.png)

**Comment by kanglu666** [comment]
updated

**Comment by slmessier** [comment]
validated successfully in KCI DEV - Updated to Ready for Staging

**Comment by Tad-Daniel** [comment]
Item Complete
