### ISSUE TITLE
QA2 PDF Form - Remove Underline Font from All Report Text Values

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#213]
- Text on PDF project description and comments sections should not be underlined. 
- **Please remove the underline font styling from all PDF Report text values.**

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validated successfully in KCI Dev - updated to "Ready for Staging"

**Comment by Tad-Daniel** [comment]
Implemented in production and working.
