### ISSUE TITLE
QA2 PDF Form - Wrap Text for Text Values that Extend Across 2+ Lines

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#214]
- Text on line item comment of PDF do not wrap.

**Comment by slmessier** [comment]
line item maximum has been increased to three lines and text has been configured accordingly.

**Comment by slmessier** [comment]
validated and tested successfully in  KCI DEV

**Comment by Tad-Daniel** [comment]
Implemented in production and working.
