### ISSUE TITLE
QA2 Inspection Form & PDF Form - Limit the "Comments/Statement of Findings/Observations" Field to 1150 characters

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#215]
From Tad:
- Ensure character limit for "Comments/Statement of Findings/Observations" is at least 1000, more is better. Add limit description to input box title.

**Comment by slmessier** [comment]
Lu has indicated that the existing character limit in the database (and therefore the UI form) is 4000 characters.

However. on the PDF form only ~1165 characters are displayed within the associated PDF field. This is resulting in truncated values appearing within the information on the PDF Report.

Please implement the following:
1. **update the system to limit users to 1150 characters on the UI QA2 Inspection Form** Use developer's discretion on how this can most effectively be acheived.
2. **update the text for the associated label on the UI to display _"(1150 character limit)"_** 
![image](https://cloud.githubusercontent.com/assets/4098544/8555104/fa007014-24bb-11e5-805b-81d149b1b1f8.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
When testing the 1150 limit, **I was able to copy/paste 1150+ characters**. (works as expected when typing, but I'm allowed to enter more than 1150 if i copy and paste:

Sample text below:
CharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharactersCharacters______beyond 1150

**Comment by kanglu666** [comment]
that's a framework issue, i can limit the type, but now way to control the copy/paste.
But, even user copy/paste more 1150 characters, the database and UI will only save 1150.

**Comment by slmessier** [comment]
Since the framework will not allow control over the number of characters in copied/pasted text, it will be sufficient if the database saves only 1150 characters.

However, the system is currently saving more than 1150 characters as displayed in the image below which was captured when attempting ot edit an existing inspection (7/14 - project #  QA2_TEST). Please update the system so that only 1150 characters are saved.

![image](https://cloud.githubusercontent.com/assets/4098544/8681317/b9d36568-2a34-11e5-8a5b-4f52f9e600ca.png)

see also issue #212

**Comment by kanglu666** [comment]
updated

**Comment by slmessier** [comment]
validated successfully in KCI DEV - Updated to Ready for Staging

**Comment by Tad-Daniel** [comment]
Implemented in production and working.
