### ISSUE TITLE
QA Toolkit - Notifications Failed to Send

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#221]
Tad has reported the system is producing a "failed to send Notifications" message for a distinct case. **Please investigate the cause of the failed notification.**

Details of the case:
-issue is being encountered after saving a QA1 inspection 
-inspection is "FINAL" and is producing a Grade of "C"
-project number = SM2165176 - MD 4 (Patuxent Beach Rd.) ....
-![image](https://cloud.githubusercontent.com/assets/4098544/9014381/010028f0-3790-11e5-8fd1-c8e63b52fec2.png)

--------------------------------------
original email
From: Tad Daniel [mailto:tdaniel@sha.state.md.us] 
Sent: Friday, July 31, 2015 1:48 PM
To: Scott Messier
Subject: error message

Can you guys look into this error message.  “Failed to send notifications”

This has been occurring on some reports but not all.  He instance below was a “C” issued by Walker Martin and should have sent some automatic notifications.  This issue has repeated itself on Walkers projects but I have not seen it in others lately.  This is a “bug” that has persisted and I cannot remember if this is already in GIT.

Thanks
![image](https://cloud.githubusercontent.com/assets/4098544/9014417/406db372-3790-11e5-9151-b4f52770a88e.png)

**Comment by Tad-Daniel** [comment]
This issue has been resolved with the user name quote fix.
