### ISSUE TITLE
EM Toolkit - Add New User Workflow - Database Error Message Displayed

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#222]
Users are reporting an error message (shown below) when attempting to add a new user to the EM Toolkit. This issue has also been replicated in KCI DEV and STAGING. Please investigate:

![image](https://cloud.githubusercontent.com/assets/4098544/10146250/ed313bcc-65f5-11e5-8615-956f6dc1444d.png)

Original support request  text (email):
![image](https://cloud.githubusercontent.com/assets/4098544/10146269/02c632da-65f6-11e5-8840-65991925b9a9.png)

**Comment by kanglu666** [comment]
fixed at KCI and SHA Staging, ready for testing

**Comment by slmessier** [comment]
this issue has been validated successfully in KCI DEV and STAGING, and may be scheduled for production release.

**Comment by slmessier** [comment]
this issue was initially implemented and tested in fall of 2015 and was successfully validated again by Scott M. on 2/3/2016 as part of a GitHub housekeeping clean-up effort. the issue will be closed.
