### ISSUE TITLE
OED Toolkits - Landing (Home) Page - New Buttons & Forms

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#223]
**Please update the OED Home / Landing Page to incorporate each of the following changes:**
![frontpage_annotated](https://cloud.githubusercontent.com/assets/4098544/10164572/3fdd8f96-6688-11e5-9778-17079fb1ae5d.png)

**Source Files:**
![qabutton](https://cloud.githubusercontent.com/assets/4098544/10164588/55e3c3b4-6688-11e5-8d1e-9a384a122b25.png)
![iembutton](https://cloud.githubusercontent.com/assets/4098544/10164589/55e64986-6688-11e5-8477-5f9f1219ab18.png)
![mdebutton](https://cloud.githubusercontent.com/assets/4098544/10164587/55e3337c-6688-11e5-8594-c02668a99ac5.png)
![biggrrequestacc](https://cloud.githubusercontent.com/assets/4098544/10164591/55e7b33e-6688-11e5-81c3-f6b939e395e3.png)
![biggrupdateacc](https://cloud.githubusercontent.com/assets/4098544/10164590/55e6b254-6688-11e5-9682-b2d87f9de949.png)
_New Account Request Form_ - [OEDtoolkits account request.docx](https://github.com/BC89/sha_oed_issues/files/4398/OEDtoolkits.account.request.docx)
_Update Account Request Form_ - [OEDtoolkits account update.docx](https://github.com/BC89/sha_oed_issues/files/4399/OEDtoolkits.account.update.docx)

**Example of Updated Home Page without Annotation:**
![frontpage](https://cloud.githubusercontent.com/assets/4098544/10164682/e5ccc214-6688-11e5-9804-8e6ae33a448e.png)

**Comment by vijme** [comment]
Updated in KCI dev. Ready for testing

**Comment by magregory** [comment]
Tested. The buttons have been implemented in the toolkit landing page and the page has been updated to specifications.

**Comment by slmessier** [comment]
Note - I am experiencing an issue downloading the documents exclusively using IE9 browser.

Otherwise the updates have been confirmed in KCI DEV and will be marked for push to STAGING.

**Comment by vijme** [comment]
Scott, I tested in IE9 on VM-OED and my system. The docs are getting downloaded. Could you elaborate what issue you had when downloading using IE9 browser?

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by Tad-Daniel** [comment]
Issue complete
