### ISSUE TITLE
MDE Toolkit - Add New User Workflow - "Unrecoverable Error" UI Message Displayed

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#224]
MDE Toolkit users are reporting that the system is issuing an "Unrecoverable Error" message in the UI after attempting to add new users to a specific project. Please see the details below:

_I am having a problem entering users for one of Nora and Steve’s projects: 21231X0 - Brownsville Rd over Branch of Israel Creek. When I add users, I get the error message below. This is unique to this one project._

![image](https://cloud.githubusercontent.com/assets/4098544/10251331/e84eef90-68fd-11e5-83f0-b1af4cbb04fe.png)

-----
(original email)

From: Scott Messier [mailto:SMessier@sha.state.md.us] 
From: Cheryl Jordon (SHA) 
Sent: Friday, October 02, 2015 10:13:35 AM 
To: Scott Messier 
Cc: 'Ed Tinney' 
Subject: FW: MDE Toolkit update 
Auto forwarded by a Rule 
Scott – could you please take a look at the below reported issue with the MDE Toolkit?  Please let Ed and I know if you have any questions. Thanks.  Cheryl

From: Ed Tinney [mailto:etinney@rkk.com] 
Sent: Friday, October 02, 2015 9:02 AM
To: Cheryl Jordon (SHA)
Subject: RE: MDE Toolkit update

Hi Cheryl,
I am having a problem entering users for one of Nora and Steve’s projects: 21231X0 - Brownsville Rd over Branch of Israel Creek. When I add users, I get the error message below. This is unique to this one project. Could you pass this along to your Toolkit folks? 
Thanks!

 ![image](https://cloud.githubusercontent.com/assets/4098544/10251331/e84eef90-68fd-11e5-83f0-b1af4cbb04fe.png)

___________________________________  
Ed Tinney 
Associate Environmental Scientist

**Comment by kanglu666** [comment]
fixed at KCI and SHA Staging, ready for testing

**Comment by slmessier** [comment]
this issue has been validated successfully in KCI DEV and STAGING, and may be scheduled for production release.

**Comment by slmessier** [comment]
this issue was initially implemented and tested in summer of 2015 and was successfully validated again by Scott M. on 2/1/2016 as part of a GitHub housekeeping clean-up effort. the issue will be closed.
