### ISSUE TITLE
Username "nicknames" email notification error

### ISSUE THREAD

**Issue by magregory** [BC89/sha_oed_issues#229]
It was found that some email notifications are not being sent due to nicknames in double quotes in the first name field for a user. When this is the case, the system fails to send a email notification to anyone in that project. There are six users that meet this case: 
Paige "Kim" Ward
Charles "Kip" Provonche
Robert "Bob" Murphy
Anthony "Tony" Chapolini
Edward "Ted" Bertch
Hollis "Tate" Cantwell

This problem can be addressed in two ways:

1. Replace the double quotes with parenthesis (ex: Robert (Bob)) for the current user’s first name in production. For new users added, we have to make sure they do not have “” in their first or last name, or we could have a code that checks and replaces “” with ().

2. Check for “” before sending email. Since there are many notifications involved in the whole system, we would have to do this check before all email notifications.

**Viji's recommended solution is option 1.**

**Comment by Tad-Daniel** [comment]
I agree with option 1 and can implement in production today by changing the user accounts.

**Comment by slmessier** [comment]
Viji - please initiate development on the additional application logic that will check for and address the "" characters during the Add New User workflow (No. 1 above).

**Comment by magregory** [comment]
Updated in KCI Dev. Quotes used in the first name field for users are converted to ( ) after saving to avoid bugs. 

![image](https://cloud.githubusercontent.com/assets/16670108/13354192/7f9ba852-dc67-11e5-95f4-a72bf49fd61e.png)

**Comment by slmessier** [comment]
this issue has been validated in DEVELOPMENT environment. Issue will be updated to "Ready for Staging".

**Comment by Tad-Daniel** [comment]
Appears to function correctly, ready for production.

**Comment by Tad-Daniel** [comment]
Implemented in production and working.
