### ISSUE TITLE
QA Toolkit - Projects Tab-->Mods Subtab - Update UX Components

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#230]
Please update the following components of the user interface for the Mods Subtab, as described within the graphic below:
![image](https://cloud.githubusercontent.com/assets/4098544/13083721/3c52bd3a-d4a4-11e5-9959-364628324b97.png)

Note: this issue was originally requested as **No. 9 (Green) within the _Requested Updates.docx_** and archived within GH issue #228 of this repository

**Comment by magregory** [comment]
There is not enough space currently to add the text on the right next to the respond button. When the text in the modification request is large there will not be enough space on the right to clearly display the added text. Viji suggested two options to deal with the space issue. 

1. Add the text as a tooltip popup. When the user hovers over the respond button a tooltip will pop up with the text "Select to add a comment or response". See screenshot below 
![image](https://cloud.githubusercontent.com/assets/16670108/13092238/d779bf34-d4cc-11e5-8dc0-5c3902d08e11.png)

2. Increase the spacing in the last column. This will move the previous column in some and may shrink the secondary response  table that inside that includes the responses conversation. 
![image](https://cloud.githubusercontent.com/assets/16670108/13092516/68faee82-d4ce-11e5-9ab3-8deae0792b10.png)

**Comment by Tad-Daniel** [comment]
Lets try for option 2 unless the space become excessive.  You could also reduce the text to "add comment or response ->"

**Comment by magregory** [comment]
Layout has been updated to new specifications. Text phrase for respond button was reduced per your suggestion. New layout screenshot below. 

![image](https://cloud.githubusercontent.com/assets/16670108/13120058/faf0deea-d579-11e5-8e77-318f822fcbad.png)

**Comment by magregory** [comment]
Updated in KCI Dev. Ready for staging.

**Comment by slmessier** [comment]
this issue has been validated in DEVELOPMENT environment. Issue will be updated to "Ready for Staging".

**Comment by Tad-Daniel** [comment]
Appears correct, ready for production.

**Comment by Tad-Daniel** [comment]
Implemented in production and working.
