### ISSUE TITLE
QA Toolkit - Mods Tab & Permits Tab - Update User Profile Permissions & Text Label

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#231]
For the Mods tab and Permits tab - please implement the following;

1. Update the user profile permissions to **allow all user roles to view the permits & Mods grids** regardless of user profile role.
2. Filter the records that are retrieved from the database and populated in the grid to be **only those records assign to the active user**, by parsing through the database relationships between modifications and/or projects.
3. **Update the text label of the _"Mods"_ Tab to display _"Modifications_"**

Note: this issue was originally requested as **No. 11 (Green) within the _Requested Updates.docx_** and archived within GH issue #228 of this repository

**Comment by magregory** [comment]
Updated in KCI Dev. Ready for staging.

**Comment by slmessier** [comment]
this issue has been validated in DEVELOPMENT environment. Issue will be updated to "Ready for Staging".

**Comment by Tad-Daniel** [comment]
Appears to function correctly, ready for production.

**Comment by Tad-Daniel** [comment]
Implemented in production and working.
