### ISSUE TITLE
QA Toolkit - BP/SS Tab-->Skipped Inspections Subtab - Add New Searchable Filter: Justification Reason

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#233]
Please add new user interface controls and functionality to provide a new searchable filter parameter for Skipped Inspection Justifications: **_Justification Reason_**

**Existing Skipped Inspection Justifications Searchable Filters:**
![image](https://cloud.githubusercontent.com/assets/4098544/13087367/7d2eade4-d4b5-11e5-8eca-b70c5d1d1968.png)

**Mockup of Updated Skipped Inspection Justifications Searchable Filters:**
![image](https://cloud.githubusercontent.com/assets/4098544/13087761/7eaa0266-d4b7-11e5-998e-b7f94b904f28.png)

Note: this issue was originally requested as **No. 6 (Purple) within the _Requested Updates.docx_** and archived within GH issue #228 of this repository

**Comment by slmessier** [comment]
this issue has been validated in DEVELOPMENT environment. Issue will be updated to "Ready for Staging".

**Comment by Tad-Daniel** [comment]
Appears to function correctly, ready for production.

**Comment by Tad-Daniel** [comment]
Implemented in production and working.
