### ISSUE TITLE
QA Toolkit - Inspections Tab-->QA2 Subtab - Add New Searchable Filter: Question Answers (Yes/No)

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#234]
Please add new user interface controls and functionality to provide a new searchable filter parameter for QA2 Inspections: **_Search by Question & Answer_**

**Existing QA2 Inspection Searchable Filters:**
![image](https://cloud.githubusercontent.com/assets/4098544/13088117/f23db096-d4b8-11e5-9210-2755ab2322c2.png)

**Mockup of Updated QA2 Inspection Searchable Filters:**
![image](https://cloud.githubusercontent.com/assets/4098544/13088462/53b8aabe-d4ba-11e5-9239-9401ba71f13c.png)

**Note: Actual text for line item questions is stored within the database and may be retrieved from there if desired.** They are listed in detail in the graphic below
![image](https://cloud.githubusercontent.com/assets/4098544/13088454/483848ca-d4ba-11e5-9f3d-75a3e623c2fa.png)

Note: this issue was originally requested as **No. 3 (Purple) within the _Requested Updates.docx_** and archived within GH issue #228 of this repository

**Comment by slmessier** [comment]
this issue has been validated in DEVELOPMENT environment. Issue will be updated to "Ready for Staging".

**Comment by Tad-Daniel** [comment]
Appears to function correctly, ready for production.

**Comment by Tad-Daniel** [comment]
Implemented in production and working.
