### ISSUE TITLE
QA Toolkit - New Inspection w. Grade "C", "D", "F" - Failed to send Email Notification

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#26]
The QA Toolkit fails to send the associated email notifications after a user has added a new inspection exclusively with the grades of "C", "D", and "F". (notifications function correctly when grade is A or B)

![image](https://cloud.githubusercontent.com/assets/4098544/3342792/dc778408-f896-11e3-9079-526e6e365e6f.png)

![image](https://cloud.githubusercontent.com/assets/4098544/3342796/f1a90e0a-f896-11e3-9e00-fcc5c8109a88.png)

![image](https://cloud.githubusercontent.com/assets/4098544/3342799/01381f46-f897-11e3-9878-b0feed50417c.png)

Steps to replicate:
1. Edit existing project --> Inspections Subtab --> Add New Inspection
2. Check the final report checkbox (which will trigger the notification when saved)
3. check the notification recipient check box(es) 
4. Check the minimum required Inspection info (1.1; 1.2; 1.3; 1.3.1; 1.3.2)
5.check the Override Grade checkbox -->set Grade to C, D, or F
6. Save inspection --> (at this point the system is expected to send the notification and is currently failing)

![image](https://cloud.githubusercontent.com/assets/4098544/3342871/af9b5c2e-f897-11e3-87d7-b5391e4f3c02.png)

**Comment by magregory** [comment]
Tested in KCI Staging. Replicated the steps listed above. Notifications were sent correctly for new inspection reports and existing reports at all grades.

**Comment by Tad-Daniel** [comment]
I believe we have resolved this issue with a recent update, this was the user name quotes issue.

**Comment by slmessier** [comment]
Note: this issue was originally requested as **No. 18 (Gray) within the _Requested Updates.docx_** and archived within GH issue #228 of this repository
![image](https://cloud.githubusercontent.com/assets/4098544/14862663/6d349ae0-0c80-11e6-863d-32cc9685315a.png)
