### ISSUE TITLE
QA Toolkit - Contact Us Hyperlink to toolkit Login Screen

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#32]
Cheryl is requesting that the 'Contact Us' mailto hyperlink be added to the log-in screen of each of the toolkits, beneath the list of "Links":

![image](https://cloud.githubusercontent.com/assets/4098544/3364171/36b78440-fb1c-11e3-853d-85b46e598881.png)

**Comment by Tad-Daniel** [comment]
Item complete
