### ISSUE TITLE
MDE Toolkit - Contact Us Hyperlink to toolkit Login Screen

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#33]
Cheryl is requesting that the 'Contact Us' mailto hyperlink be added to the log-in screen of each of the toolkits, beneath the list of "Links":

![image](https://cloud.githubusercontent.com/assets/4098544/3365312/f97c8cf0-fb2b-11e3-846b-679d2d24b76f.png)

**Comment by Tad-Daniel** [comment]
Implemented in production and working.
