### ISSUE TITLE
EM Toolkit - Contact Us Hyperlink to toolkit Login Screen

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#34]
Cheryl is requesting that the 'Contact Us' mailto hyperlink be added to the log-in screen of each of the toolkits, beneath the list of "Links":

![image](https://cloud.githubusercontent.com/assets/4098544/3365305/cab6ad88-fb2b-11e3-81dc-27e7532c8de5.png)

**Comment by Tad-Daniel** [comment]
Implemented in production and working.
