### ISSUE TITLE
QA Toolkit - Add "Title" Beside Name in Notification List

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#46]
1.	Add the “Title” beside the name in the notification list in all areas. (reports, communication)

![image](https://cloud.githubusercontent.com/assets/4098544/3510676/da812fd0-06a8-11e4-927b-4b938cd170e5.png)

**Comment by slmessier** [comment]
Successfully validated in Staging - will be marked for release into Production (using "Ready for Production" label withing GitHub.

**Comment by slmessier** [comment]
Validated in Production. Will assign to Tad for validation and closure of issue in GitHub.

**Comment by Tad-Daniel** [comment]
Looks good everywhere that it is implemented.  Would like to add this to the QA reports  (OOC-61 template)

![qa form](https://cloud.githubusercontent.com/assets/7913678/5861597/c0a594da-a238-11e4-8c61-7a63a4a5f93a.png)

**Comment by slmessier** [comment]
This is a screen in the UI at the bottom of a Quality Assurance report. From the schedule an inspector creates a QA report and these names show up when they check the final box at the top of the report.

Specific steps to access below:
1. open a new QA report
2. save as a draft
3. **click final box at the top of the report**
4. the name selection will show up at the bottom of the report for user to select additional recipients of notifications.
