### ISSUE TITLE
QA Toolkit - Tracking & Reporting Functionality (Similar to MDE Permit Review)

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#47]
1. Create tracking and reporting method for modification in the system.  Adapt parts of the MDE Toolkit related to permit review that can be used in the QA toolkit for modification review.  (See Mock-up)
  1. Add “Alert me of new messages” option to user subscriptions just like the EM Toolkit.  
  2. Possible electronic version of OO C-62 within the toolkit that can be filled out and signed.  (Template)
  3. Tab in project record to store modification information  
  4. Add the category of “Modification” to the Type of Documents. 
  5. Ability to Print records of modification
![image](https://cloud.githubusercontent.com/assets/4098544/3510740/62137ef8-06a9-11e4-9930-8a7fbf6f4424.png)

**Comment by Tad-Daniel** [comment]
This item is complete.
