### ISSUE TITLE
QA Toolkit - Remove Contacts Tab from Project record

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#49]
1.Remove Contacts tab in project record

![image](https://cloud.githubusercontent.com/assets/4098544/3510811/11655b74-06aa-11e4-81d9-d6de2909ab73.png)

**Comment by slmessier** [comment]
Successfully validated in Staging - will be marked for release into Production (using "Ready for Production" label withing GitHub.

**Comment by slmessier** [comment]
Validated in Production. Will assign to Tad for validation and closure of issue in GitHub.

**Comment by Tad-Daniel** [comment]
Looks good, will close the issue
