### ISSUE TITLE
QA Toolkit - Redesign User Subtab in Project Record

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#50]
5.	Rename User Tab in the project record to Stakeholders.  The tab should have Name, company/agency, email, phone, title and role (if not enough room then role may be omitted) 

![image](https://cloud.githubusercontent.com/assets/4098544/3511965/629d2274-06b4-11e4-9105-a64aa7ba21c4.png)

**Comment by slmessier** [comment]
Successfully validated in Staging - will be marked for release into Production (using "Ready for Production" label withing GitHub.

**Comment by slmessier** [comment]
Validated in Production. Will assign to Tad for validation and closure of issue in GitHub.

**Comment by Tad-Daniel** [comment]
Looks good, will close issue
