### ISSUE TITLE
QA Toolkit - Hide “labels” from the documents items across the toolkit

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#51]
6.	Remove “Labels” from document description?
![image](https://cloud.githubusercontent.com/assets/4098544/3512703/1f53fc6a-06bc-11e4-8195-34ba329da799.png)

![image](https://cloud.githubusercontent.com/assets/4098544/3512694/126464e0-06bc-11e4-8a71-2c6b1fc8180d.png)

**Comment by slmessier** [comment]
Successfully validated in Staging - will be marked for release into Production (using "Ready for Production" label withing GitHub.

**Comment by slmessier** [comment]
Validated in Production. Will assign to Tad for validation and closure of issue in GitHub.

**Comment by Tad-Daniel** [comment]
Good,  Will Close
