### ISSUE TITLE
QA Toolkit - (2) New Project Document Types: "Permit" & "NPDES Report"

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#52]
7.	Add the category of “Permit” to the Type of Documents.

![image](https://cloud.githubusercontent.com/assets/4098544/3512736/818a8a2a-06bc-11e4-875b-8d007ba61fb4.png)

![image](https://cloud.githubusercontent.com/assets/4098544/3512750/b9f8e640-06bc-11e4-9860-fb35cfd6a6bf.png)

**Comment by slmessier** [comment]
There is an issue (occurring exclusively in Staging) where several blank values appear within the dropdown. 

![image](https://cloud.githubusercontent.com/assets/4098544/5686085/1b5c5cc2-980e-11e4-9f49-d9ea52ae56cd.png)


Please investigate and reconcile, then re-assign to me for validation.

**Comment by slmessier** [comment]
Successfully validated in Staging - will be marked for release into Production (using "Ready for Production" label withing GitHub.

**Comment by slmessier** [comment]
Validated in Production. Will assign to Tad for validation and closure of issue in GitHub.

**Comment by Tad-Daniel** [comment]
Good,  issue closed
