### ISSUE TITLE
QA Toolkit - Projects - Remove Subtabs: Issues & Resources

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#53]
8.	Remove tabs for “issues” and “resources” 
![image](https://cloud.githubusercontent.com/assets/4098544/3512890/dba71bbc-06bd-11e4-9de4-b8c435ceee3f.png)

![image](https://cloud.githubusercontent.com/assets/4098544/3512887/d3283f02-06bd-11e4-81de-87a6e5c1a52a.png)

**Comment by slmessier** [comment]
Successfully validated in Staging - will be marked for release into Production (using "Ready for Production" label withing GitHub.

**Comment by slmessier** [comment]
Validated in Production. Will assign to Tad for validation and closure of issue in GitHub.

**Comment by Tad-Daniel** [comment]
Looks good, will close the issue
