### ISSUE TITLE
QA Toolkit - Projects - Search Panel Functionality - Remove Member/Role 

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#57]
d.	Remove “Member/Role” from Project list search panel.

![image](https://cloud.githubusercontent.com/assets/4098544/3513890/1e2d4606-06c7-11e4-8475-a262cc2c6f53.png)

**Comment by Tad-Daniel** [comment]
Closing issue,  The member / role search is to be left as is.
