### ISSUE TITLE
QA Toolkit - Projects - Remove "ESC" from "ESC Superintendent" label on UI

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#58]
Remove the word “ESC” from “ESC Superintendent” in the project record.

![image](https://cloud.githubusercontent.com/assets/4098544/3513981/130ab3a2-06c8-11e4-95c9-150bd08db153.png)

**Comment by slmessier** [comment]
Successfully validated in Staging - will be marked for release into Production (using "Ready for Production" label withing GitHub.

**Comment by slmessier** [comment]
Validated in Production. Will assign to Tad for validation and closure of issue in GitHub.

**Comment by Tad-Daniel** [comment]
Looks Good,  will close the issue
