### ISSUE TITLE
QA Toolkit - Inspection Templates - Relocate Launch Point to Within Admin Menu

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#61]
Move the “Templates” menu to the “Admin” section. (Currently launched from the Inspections Tab)
(Update the system so that Inspection Templates is accessed exclusively from within the ADMIN menu - assuming only by authorized users with administrator permissions)

![image](https://cloud.githubusercontent.com/assets/4098544/3514391/c709b29c-06cb-11e4-9c78-3a207c62f4e0.png)

**Comment by Tad-Daniel** [comment]
This item has been completed
