### ISSUE TITLE
QA Toolkit - Admin User List - Enable Print Search Results (PDF Report)

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#63]
Print User list based on search criteria.  The print button already exists but is not active.

(admin menu --> user List --> (with active search within search panel)
![image](https://cloud.githubusercontent.com/assets/4098544/3514562/26035a86-06cd-11e4-8adc-a831d4db45e5.png)

**Comment by magregory** [comment]
The printing functionality can be implemented but the current PDF that results from the table shown on the user list is not fitting properly on one page. Is it a possibility to eliminate a column in an attempt to clean up the PDF linked to this function?

**Comment by magregory** [comment]
The resulting PDF has been updated with appropriate spacing and layout without eliminating columns. 

![image](https://cloud.githubusercontent.com/assets/16670108/12795208/e470ae0a-ca86-11e5-99cd-8bfeb8170ae1.png)

**Comment by slmessier** [comment]
these updates have been confirmed in KCI DEV and will be marked for push to STAGING targeting 2/4/16 for release.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by Tad-Daniel** [comment]
Could we update the logic so that when the interface is sorted by a particular column on screen the sorting should be reflected in the PDF.

**Comment by vijme** [comment]
Fixed. please test

**Comment by magregory** [comment]
Updated in KCI Dev. Sorting is reflected accurately in the pdf created by print button.

**Comment by slmessier** [comment]
this issue has been validated in DEVELOPMENT environment. Issue will be updated to "Ready for Staging".

**Comment by Tad-Daniel** [comment]
Appears to function correctly, ready for production.

**Comment by Tad-Daniel** [comment]
Implemented in production and working.
