### ISSUE TITLE
QA Toolkit - Update Permit Capabilities so that a related Project is NOT Required

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#71]
From: Tad Daniel [mailto:tdaniel@sha.state.md.us] 
Sent: Friday, October 24, 2014 2:16 PM
To: Scott Messier
Cc: Heidi Hammel
Subject: item not related to modifications system

One an unrelated item it was mentioned that you guys can work on minor items under the maintenance issues hours.
 
Could this be a part of that (if its a minor adjustment).  I would like to change the logic in the new permit entry section so that the system does not require a project to be associated with the permit....
 
See attached picture of the current warning.....
 
This would allow the use of the system as a type of drop-box for permits prior to a project starting and then a project can be associated later when the field work actually starts.
 
Thanks
 
Tad Daniel
![new permit screen](https://cloud.githubusercontent.com/assets/4098544/4774246/414f0032-5bab-11e4-9cbc-a36ae3674ae2.png)

**Comment by magregory** [comment]
Updated at KCI Dev. Ready for testing in staging.

**Comment by slmessier** [comment]
I was also able to successfully validate in KCI DEV

**Comment by vijme** [comment]
Tested fine in staging

**Comment by Tad-Daniel** [comment]
Working well in staging

**Comment by Tad-Daniel** [comment]
Issue complete

**Comment by slmessier** [comment]
Note: this issue was originally requested as **No. 23 (Gray) within the _Requested Updates.docx_** and archived within GH issue #228 of this repository
![image](https://cloud.githubusercontent.com/assets/4098544/14060539/153ef52a-f33e-11e5-8979-3921f039e139.png)
![image](https://cloud.githubusercontent.com/assets/4098544/14862663/6d349ae0-0c80-11e6-863d-32cc9685315a.png)
