### ISSUE TITLE
QA Toolkit - Update Title on Reference Documents Page

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#72]
From: Tad Daniel [mailto:tdaniel@sha.state.md.us] 
Sent: Wednesday, November 12, 2014 12:23 PM
To: Scott Messier
Cc: Cheryl Jordon (SHA); Sandy Hertz; Heidi Hammel; Scott Messier
Subject: RE: QA Toolkit - Modification Request Enhancements - Updated Wireframes V1.1

8.	Change page title in Reference documents to match menu title.

![image](https://cloud.githubusercontent.com/assets/4098544/5269131/fcee1242-7a2d-11e4-863d-04939baac09c.png)

**Comment by slmessier** [comment]
Successfully validated in Staging - will be marked for release into Production (using "Ready for Production" label withing GitHub.

**Comment by slmessier** [comment]
Validated in Production. Will assign to Tad for validation and closure of issue in GitHub.

**Comment by Tad-Daniel** [comment]
Good,  Issue closed
