### ISSUE TITLE
QA Toolkit - Add "Grades" column to Project List

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#73]
# Please add "Grades" column to Project List as outlined within the wireframes Modification Request Enhancements.

## Snapshot of applicable screen (002) from Wireframes below:
![image](https://cloud.githubusercontent.com/assets/4098544/5299123/a7a419c0-7b91-11e4-813f-4d7426a5e455.png)

**Average Grade**: calculate by averaging the grade values of ***Inspection*** records associated to the applicable ***Project***

**Recent Grade**: calculate by displaying the single grade value of the ***most recently dated  Inspection*** record associated to the applicable ***Project***

**Comment by kanglu666** [comment]
done at KCI, please test

**Comment by slmessier** [comment]
this issue was initially implemented and tested in winter of 2015 and was successfully validated again by Scott M. on 2/1/2016 as part of a GitHub housekeeping clean-up effort. the issue will be closed.
