### ISSUE TITLE
QA Toolkit - Update Toolkit Banner

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#74]
# Replace the QA Toolkit Banner using the attached graphic. 
![qabanner](https://cloud.githubusercontent.com/assets/4098544/5417423/0bbad180-8207-11e4-9707-09a644fc972c.gif)

**Comment by slmessier** [comment]
Successfully validated in Staging - will be marked for release into Production (using "Ready for Production" label withing GitHub.

**Comment by slmessier** [comment]
Validated in Production. Will assign to Tad for validation and closure of issue in GitHub.

**Comment by Tad-Daniel** [comment]
Good, Will Close
