### ISSUE TITLE
EM Toolkit - Update Toolkit Banner

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#75]
# Replace the EM Toolkit Banner using the attached graphic.
![emtoolkit-a](https://cloud.githubusercontent.com/assets/4098544/5417456/7199004e-8207-11e4-855f-ea6eedf1818e.gif)

**Comment by slmessier** [comment]
Successfully validated in Staging - will be marked for release into Production (using "Ready for Production" label withing GitHub.

**Comment by slmessier** [comment]
Validated in Production. Will assign to Tad for validation and closure of issue in GitHub.

**Comment by Tad-Daniel** [comment]
Good, Will Close
