### ISSUE TITLE
MDE Toolkit - Update Toolkit Banner

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#76]
Replace the MDE Toolkit Banner using the attached graphic.
![mdetoolkit](https://cloud.githubusercontent.com/assets/4098544/5417466/923cc7b8-8207-11e4-85dd-e417bcb19956.jpg)

**Comment by slmessier** [comment]
Successfully validated in Staging - will be marked for release into Production (using "Ready for Production" label withing GitHub.

**Comment by slmessier** [comment]
Validated in Production. Will assign to Tad for validation and closure of issue in GitHub.

**Comment by Tad-Daniel** [comment]
Good, Issue Closed
