### ISSUE TITLE
QA Toolkit - Login Screen - Update URL Links

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#77]
Update links to the following
1. OED Toolkit Portal Home - http://www.oedtoolkits.net/ (**note: already exists**)
2. **Maryland Department of the Environment - http://www.mde.state.md.us/Pages/Home.aspx**
2A. **(remove previously existing URL completely - Modification and Amendment of Environmental Permits on Design-Build Projects)**
3.	Environmental Protection Agency - http://www.epa.gov/ (**note: already exists**)
4. International Erosion Control Assoc. http://www.ieca.org/ (**note: already exists**)
5. National Highway Institute - http://www.nhi.fhwa.dot.gov/ (**note: already exists**)
6. FHWA Environmental Guidebook - http://www.environment.fhwa.dot.gov/guidebook/index.asp (**note: already exists**)
7. COMAR Online - http://www.dsd.state.md.us/comar/ (**note: already exists**)

![image](https://cloud.githubusercontent.com/assets/4098544/5417599/03bc6e7e-8209-11e4-86a9-173910f055e5.png)

**Comment by slmessier** [comment]
Successfully validated in Staging - will be marked for release into Production (using "Ready for Production" label withing GitHub.

**Comment by slmessier** [comment]
Validated in Production. Will assign to Tad for validation and closure of issue in GitHub.

**Comment by Tad-Daniel** [comment]
Looks good except the font of the titles be reduced to match the font size in the EM and MDE front pages, add a space between the titles and graphics for better aesthetics.  Remove RSS feeds below the weather on all toolkits.

![qa login](https://cloud.githubusercontent.com/assets/7913678/5861714/04c748ce-a23a-11e4-868d-d8429d2b837f.png)

**Comment by slmessier** [comment]
***For the QA Toolkit*** - please:
1.**Update font size of the headings to match the font size of the headings in the EM and MDE toolkits front pages** ![image](https://cloud.githubusercontent.com/assets/4098544/5918960/bae22668-a5fc-11e4-87eb-951db2633e32.png)

2.**Add a blank line between the headings and the graphics to provide some vertical space in the layout** ![image](https://cloud.githubusercontent.com/assets/4098544/5918982/ec86f040-a5fc-11e4-8ee3-ac0651835590.png)

3.**Remove the RSS feeds below the weather feed completely.**

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
Can the font size of these headings in the  QA Toolkit be reduced to match the EM toolkit?

EM tookit:
![image](https://cloud.githubusercontent.com/assets/4098544/5923425/72843332-a621-11e4-92b1-a64d159da8a8.png)


QA Toolkit:
![image](https://cloud.githubusercontent.com/assets/4098544/5923420/617f5dbe-a621-11e4-9ab3-86bd53747410.png)

**Comment by kanglu666** [comment]
already done, please test

**Comment by slmessier** [comment]
validated successfully - will be marked as "Ready for Staging"

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
