### ISSUE TITLE
QA Toolkit - Login Screen - Add Weather Feed

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#78]
Add weather banner from www.forcast.io
reference http://blog.forecast.io/forecast-embeds/ if necessary

![image](https://cloud.githubusercontent.com/assets/4098544/5418156/2bab585a-820e-11e4-93b0-1d601a967f44.png)

**Comment by slmessier** [comment]
Successfully validated in Staging - will be marked for release into Production (using "Ready for Production" label withing GitHub.

**Comment by slmessier** [comment]
Validated in Production. Will assign to Tad for validation and closure of issue in GitHub.

**Comment by Tad-Daniel** [comment]
Good, will close
