### ISSUE TITLE
QA Toolkit - Login Screen - Add Responsible Personnel Certification Info

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#79]
Add Responsible Personnel Certification Info using attached graphic:
![rpc card](https://cloud.githubusercontent.com/assets/4098544/5418433/165fdc62-8210-11e4-8a74-5f12f80e2742.png)

![image](https://cloud.githubusercontent.com/assets/4098544/5418444/308db5dc-8210-11e4-8c01-c431d13f7c89.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
On the Log-in page please update the URL hyperlink address for the MDE Responsible Personnel Certification. 

New URL hyperlink:
http://mderpc.mde.state.md.us/Account/login.aspx

![image](https://cloud.githubusercontent.com/assets/4098544/7421879/41dae810-ef56-11e4-90d4-017384d121d2.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validated successfully in KCI Dev - updated to Ready for STAGING

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
