### ISSUE TITLE
QA Toolkit - Develop New System Role: Project Engineer

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#82]
Develop & implement a new system role titled, "Project Engineer" with the following capabilities:

1. **Import the base capabilities of the existing "Reviewer" role** to function as the base capabilities for the new "Project Engineer" role.
1. **Add new  capability - Attach Supporting Documents**
2. **Add new  capability - Track Project Incentive Funds**

For reference, a complete list of general capability for the new Project Engineer role:
- Add Supporting Documents - **New  capability**
- Track Project Incentive Funds - **New  capability**
- Download Standard Forms / Templates – (inherited from Reviewer role)
- Download Standard Forms / Templates – (inherited from Reviewer role)
- Query/Print QA Inspection Reports – (inherited from Reviewer role)
- Query/Print  Project Issues – (inherited from Reviewer role)
- Edit / Print Project Info – (inherited from Reviewer role)
  - View/Add Communications – (inherited from Reviewer role)

**Comment by kanglu666** [comment]
Project Engineer role has been added into current system, please test

**Comment by Tad-Daniel** [comment]
This item is complete
