### ISSUE TITLE
QA Toolkit - Error Adding New & Updating Existing Projects & Inspections

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#83]
In testing within the development environment (http://oed.kci.com/SHAPORTAL) i have encountered an issue with the following capabilities:
1. Add New Project
2. Update Existing Project
3. Add New Inspection
4. Update Existing Inspection

for project-based errors:
![image](https://cloud.githubusercontent.com/assets/4098544/5686928/68e2e07c-9815-11e4-866d-5905c1215068.png)

for inspection-based errors:
![image](https://cloud.githubusercontent.com/assets/4098544/5686900/4617bcc0-9815-11e4-941e-b2f5c24f0184.png)

**Comment by slmessier** [comment]
Validated successfully within KCI-hosted development site. This issue will be labelled as "Ready for Staging".

**Comment by slmessier** [comment]
Successfully validated in Staging - will be marked for release into Production (using "Ready for Production" label withing GitHub.

**Comment by slmessier** [comment]
Validated in Production. Will assign to Tad for validation and closure of issue in GitHub.

**Comment by Tad-Daniel** [comment]
Validated as working.  will close.
