### ISSUE TITLE
Modification Request Form - Error Sending Email

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#84]
the system is producing an error when I attempt to submit a new Modification using the initial Modification Request Form. 
See graphic below (note the **error message at the top of the form** which is displayed after clicking on the Submit button. Also note that **the contractor, SHA project Engineer, and Rec/QA fields have not been populated - all other fields have been populated**)

![image](https://cloud.githubusercontent.com/assets/4098544/5842148/8aa15252-a170-11e4-9c11-960caaa7bdd6.png)

**Comment by kanglu666** [comment]
1: send email notification is not working at KCI because it's using SHA SMTP server. please test this at SHA.
2 :the contractor, SHA project Engineer, and Rec/QA fields have not been populated: because you dont put these info in the form.

**Comment by slmessier** [comment]
Tad - I belive this issue was resolved some time ago. Please confirm and close if applicable.

**Comment by Tad-Daniel** [comment]
Issue resolved
