### ISSUE TITLE
Modification Request Form - Remove Icons for Delete / Update Project

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#85]
Remove icons for delete project and update project functions
 
![image](https://cloud.githubusercontent.com/assets/4098544/5842978/2da0930e-a177-11e4-9fa2-7f33c90fe8a9.png)

**Comment by kanglu666** [comment]
this tool is what the current system used for selecting project, that is being used in lot places in current system, such as the permits. i prefer to keep it in MOD request form for the same using experience as the rest.

**Comment by slmessier** [comment]
Please remove the associated icons as discussed during the recent team meeting - thank you!

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validated successfully in KCI DEV - updated to "Ready for staging"

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
