### ISSUE TITLE
Modification Request Form - Update Layout of Activity Location Checkboxes

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#87]
1. **Update layout and order of all checkboxes to match wireframe** (wireframe with specified layout is below)
![image](https://cloud.githubusercontent.com/assets/4098544/5843028/829408dc-a177-11e4-9821-63289a1e5280.png)

2. **Add additional text to the associated checkboxes** as described below:
![image](https://cloud.githubusercontent.com/assets/4098544/5843046/a45d7430-a177-11e4-958b-db994c8f77d2.png)

3. **Update form to require users to enter text when the user clicks submit and the ‘Other’** checkbox is selected. (currently users can submit without providing the text)

**Comment by kanglu666** [comment]
updated

**Comment by slmessier** [comment]
validated successfully - will be marked as "Ready for Staging"

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
