### ISSUE TITLE
Modification Request Form - Error on Authentication of Contractor, SHA Project Engineer, & REC/QA

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#88]
Error Message when attempting to Authenticate as Contractor, SHA Engineer, & REC/QA: **“Not Authenticated, Try Again”**

![image](https://cloud.githubusercontent.com/assets/4098544/5843183/b6a90aae-a178-11e4-9e73-945a062af09b.png)

**Comment by kanglu666** [comment]
what's wrong with this?

**Comment by kanglu666** [comment]
the error message means you are not contractor and you want to authenticate the contractor field.

**Comment by slmessier** [comment]
The system should accept any active user who has supplied accurate user credentials, by first authenticating the credentials, and then if successful, associating that user to the modification.

**Comment by kanglu666** [comment]
So you mean, the contractor field can be any SHA active user with accurate user credentials, even the user has no contractor role?
what i'm thinking is the contractor field must be an user who is contractor role, pe filed must be an user has project engineer role. QA field must be user who has package approval role from the design.

**Comment by slmessier** [comment]
Correct it can be any user. Those roles (Contractor, SHA Project Engineer, QA/REC) do not exist within the available current system roles.

**Comment by kanglu666** [comment]
I think we should discuss this. 
Contractor role is in the current system.
SHA Project Engineer has been added in the system . see QA Toolkit - Develop New System Role: Project Engineer #82
QA/REC is the users who have package approval permission (from the design wireframe)

**Comment by slmessier** [comment]
I was mistaken - you are correct about the QA/REC role being linked to package approver permission. However the other 2 roles (Contractor & SHA Project Engineer) are not to be linked to any system roles.

**Comment by kanglu666** [comment]
From our last meeting for OED, i have been told when current log in user create an new MOD request, when need the contractor and PE user to do the authentication, they will be sit together to do this. Since this is not a bug, more like a design,  i think you should clarify this with Tad.

**Comment by kanglu666** [comment]
as requested, contractor and PE field will accept all active SHA user authentication. please test

**Comment by slmessier** [comment]
**Please add a message within the REC/QA input field that is displayed when a user with invalid user permissions has been authenticated.** 
![image](https://cloud.githubusercontent.com/assets/4098544/5919724/84e56586-a604-11e4-88fb-bf4557c979e8.png)

1. Specifically, the message  would be triggered when the user has successfully authenticated but does not have the "Package Approver" permission activated.
2. The message text should be, "*User is not Package Approver*"

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validated successfully - marked as "Ready for Staging"

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
