### ISSUE TITLE
QA Toolkit - Notifications are not functional

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#90]
Users are indicating that system notifications are not working:

From: Tad Daniel [mailto:tdaniel@sha.state.md.us] 
Sent: Friday, January 23, 2015 1:00 PM
To: Scott Messier
Subject: Noticed toolkit issues

Scott
 
The team has noticed two issues after the recent update.
 
**Everyone is experiencing an error that notification are not sent.  This is happening in every part of the system**
 
...
 
Thanks

**Comment by slmessier** [comment]
Validated in Staging - will be marked for Push to Production

**Comment by slmessier** [comment]
This issue has been validated successfully in PRODUCTION. This issue will be assigned to Tad for verification. Tad please update the issue to be close if applicable.

**Comment by Tad-Daniel** [comment]
This function is working properly in production.  Will close issue.
