### ISSUE TITLE
Modification Request Form - Display Project Details After Submit when Form is Completed

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#91]
After  the user has supplied all the required information and clicked submit (Form has been completed), the system should display the project details page with the Modifications Tab selected. Currently the system displays the Modification request form:

Current screen after submit (when all info supplied):
![image](https://cloud.githubusercontent.com/assets/4098544/5920641/1585cb56-a60c-11e4-90e7-f6d1857e2e0d.png)

Revised screen after submit (when all info supplied):
![image](https://cloud.githubusercontent.com/assets/4098544/5920652/2cfac962-a60c-11e4-8481-07dd77c16812.png)

**Comment by slmessier** [comment]
Please also implement this update after the  Modification Response Form has been fully completed and submitted (user clicks submit)

Currently system displays completed Mod Response form (see below), **please update to display the Project Details with Mods tab selected**:

![image](https://cloud.githubusercontent.com/assets/4098544/5921416/d1d86b2e-a611-11e4-9e62-1f0fe404617a.png)

**Comment by kanglu666** [comment]
the current system is doing the same work flow, please see the add new permit function. after new permit submitted, it keeps stay the permit details page, not navigate to the project details page, that's the current system does.

**Comment by Tad-Daniel** [comment]
Item no longer an issue, resolved through other items.
