### ISSUE TITLE
Project Details - Mods SubTab - Remove/Disable Edit Icon when Request Status ≠ Pre-Submittal

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#92]
After the Modification Request is submitted with all required information, the system considered the Package Status = "In Development" and is not longer in a "Pre-Submittal" status. At this point in the workflow **(when Package Status ≠ Pre-Submittal)  the Edit button to edit the request should be disabled or removed from the Mods subtab**. 

**Please update the system to automatically disable or remove the edit icon when Package Status ≠ Pre-Submittal.** See below:

![image](https://cloud.githubusercontent.com/assets/4098544/5921124/9eb44e7c-a60f-11e4-8403-627f4d369c03.png)

**Comment by slmessier** [comment]
Icon to access existing request needs to remain available to provide access to document attachments, but should be view-only. Rather than remove the icon, can all fields be disabled on the respective forms? We should brainstorm possible solutions in our next status meeting.

**Comment by slmessier** [comment]
This solution - regardless of what implementation is identified as ideal - also needs to be implemented after the entire request has been approved as the system should allow no additional editing after that is the case.

**Comment by slmessier** [comment]
Please update the system with the solution that was discussed in the recent team meeting and described below:

1. **Apply to Modification Request & Modification Response Forms** when users access the form after the associated records have been committed (users have clicked submit for each form, the system has saved the associated records, and then users have clicked on the icon to access the saved information)
2. **Disable all input fields, checkboxes, other interactive user-input controls**
3. **Add Banner Message at top of each form  - "Information below has been committed to the system and is read-only"**

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validated successfully in KCI DEV - updated to "Ready for Staging"

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
