### ISSUE TITLE
Modification Request Status - Erroneously Updated to "Approved" after first response is submitted

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#93]
Currently the system is automatically updating the Overall Request Status to "Approved" at the incorrect point in the overall workflow.

**Currently the system updates the request status to Approved after the first response has been submitted - this is erroneous.**

![image](https://cloud.githubusercontent.com/assets/4098544/5921807/7f4df236-a614-11e4-9666-65bcc75fe056.png)

**The request status should only change when users with Admin-Request Approver permissions have updated the status for each of the applicable Agency groups that have been associated to the request.**

**Comment by kanglu666** [comment]
fixed

**Comment by slmessier** [comment]
Validated successfully - ready for staging

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
