### ISSUE TITLE
Modification Response Form - Re-Authentication Required When Package Status updated to Approved

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#95]
When a user updates the Package Status to "Approved" and clicks Submit, the system should prompt the user for Authentication credentials (it will be the same user that is logged in, but stakeholders would like to re-authenticate at this step in the workflow).

If authentication credentials fail, please provide an appropriate message to indicate failure - "Credentials not Authorized"

Please reference the wireframe below:
![image](https://cloud.githubusercontent.com/assets/4098544/5928658/dcceaf6e-a64a-11e4-9cd9-f78be9059fce.png)

**Comment by kanglu666** [comment]
the re-authentication can not happen from the "Submit" button.
let's say, this request has already been package approved, when user create an new response, click the Submit button, then system will do the re-authentication again. if they do need the re-authentication function, we need do it as the way request form using for contractor, pe and rec/qa

**Comment by slmessier** [comment]
This issue also applies to the Request Approver permission after updating the status within any of the associated Agency Dropdowns (upon clicking submit).

**Comment by slmessier** [comment]
Please update the system with the functionality that was discussed during the recent team meeting.

**This issue represents the highest priority for development.**

Reference the associated whiteboard screenshot below:
![package requestapprover_revised_20150129](https://cloud.githubusercontent.com/assets/4098544/5976020/02cfb52e-a857-11e4-80da-e83b620c9acb.jpg)

**Comment by kanglu666** [comment]
done, please test.

**Comment by slmessier** [comment]
validated successfully in KCI DEV - updated to "Ready for Staging"

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
