### ISSUE TITLE
Modification Response Form - Disable Agency Dropdowns that are Unchecked

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#96]
Agency dropdowns should remain disabled unless the associated checkbox has been selected by a Package Approver (see error in red below)
![image](https://cloud.githubusercontent.com/assets/4098544/5928805/ee5aee68-a64b-11e4-8c15-8eaed0a59e4f.png)

**Comment by kanglu666** [comment]
1: packager status drop down is controlled by login user packager approval permission
2: the check boxes are controlled by the packager status drop down 
3: the Agency dropdowns are controlled by the login in user member groups.

So the package approver can check agency boxes, but if he is not a agency membership, he can not do the dropdown. The agency member can do the dropdown, but if he is not package approver, he can not do the checkbox. 

that's how our database schema works this way.. cant use the checkbox control the dropdown.

**Comment by slmessier** [comment]
The design calls for agency dropdown functionality to link these dropdowns to **3 pieces of logic** the (1) Admin Agency checkbox selection that is set by Package Approver (shown in blue), (2)  the active user's Admin Request Approver permission membership (shown in red), and (3) the Admin Agency Group Membership for Request Approver (shown in red).

If the checkbox has not been selected (By Package Approver), then dropdown should always remain disabled.
The database and system should be re-engineered appropriately to accommodate this design that considers all 3 pieces of logic.
![image](https://cloud.githubusercontent.com/assets/4098544/5943616/72e2cb0e-a6ee-11e4-8b4e-d41f612d31c6.png)

**Comment by kanglu666** [comment]
checkboxs are now able to control dropdowns. please test

**Comment by slmessier** [comment]
this issue may be obsolete pending resolution of issue #95. It will remain open until that time when it can be assessed further.

**Comment by slmessier** [comment]
this issue no longer applies and will be closed.
