### ISSUE TITLE
Modification Response Form - Environmental Programs Checkbox Selection does not persist

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#97]
When I am logged in as a Package Approver, i am able to select the Environmental Programs checkbox and click submit, but the checkbox does not persist as selected. see below

Updated to selected, click submit:
![image](https://cloud.githubusercontent.com/assets/4098544/5928901/eec799ea-a64c-11e4-833a-4c7cb56315ac.png)

View/edit response again after submit:
![image](https://cloud.githubusercontent.com/assets/4098544/5928917/04c54f12-a64d-11e4-9bf1-e79292d5acac.png)

**Comment by kanglu666** [comment]
fixed

**Comment by slmessier** [comment]
validated successfully - marked as "Ready for Staging"

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
