### ISSUE TITLE
Modification Response Form - Automatically update Agency Dropdown to "Submitted for Approval" upon Checkbox Selection

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#98]
**When the Package Approver has selected a checkbox for the Agency Dropdowns and clicks submit, the system should automatically update the Request Status for the associated dropdowns to "Submitted for Approval".**

The update to the status value **should be triggered when the PAckage Approver clicks the submit button**

![image](https://cloud.githubusercontent.com/assets/4098544/5929075/73d36adc-a64e-11e4-9b2f-a34c9b131785.png)

![image](https://cloud.githubusercontent.com/assets/4098544/5929084/8d572ee4-a64e-11e4-89c6-67e5de8739ad.png)

**Comment by kanglu666** [comment]
updated.

**Comment by slmessier** [comment]
Please update the system to display the text "submitted for approval" only **after** the Package Status is "approved". **the system should display no text in the agency dropdowns prior to this condition being met. When package status  = "In Development" or package status = "Pre Submittal" the system shuld display no text in the agency dropdowns.**

**Comment by kanglu666** [comment]
Our data model has no mod approval status that is empty string, and also the check box has no control for the dropdowns, so use the package status and check box to control the dropdown value is not workable.
solution and Updated: 
per the discussion from our last meeting, the agency groups will be hidden if the log in user is not in that group.

**Comment by slmessier** [comment]
this issue has been resolved by revised UI as described in #95

**Comment by slmessier** [comment]
this issue has been implemented and validated in SHA PRODUCTION and will be closed.
