### ISSUE TITLE
QA Toolkit - Signature Box Size Too Small

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#99]
From: Tad Daniel [mailto:tdaniel@sha.state.md.us] 
Sent: Wednesday, January 28, 2015 7:53 AM
To: Scott Messier
Subject: FW: Signature box on the toolkit

Scott

Can you guys look into the signature box on the QA form in the toolkit....

It appears to have become a small space instead of a large space tp sign in.  This happened at the last update but users only noticed it as the cache cleared on there machines.

Screenshot attached

Thanks

Tad Daniel

Environmental Programs Division
Regional Environmental Coordinator Team Leader
410-365-0164

**Comment by slmessier** [comment]
From: Scott Messier 
Sent: Wednesday, January 28, 2015 8:19 AM
To: 'Tad Daniel'
Cc: Heidi Hammel
Subject: RE: Signature box on the toolkit

Hi Tad,

We can certainly address this issue if its stemming from something in the system. The problem I'm experiencing currently is that everything is appearing as expected when I try to access the signatures (see below), so it seems we may have to coordinate to perform a bit more troubleshooting to hunt down the source of the issue.

Specifically, I’ve examined in both DEV and PRODUCTION environments using IE ( version9) and Chrome (version 40.0.2214.93) in each. For all cases I’m seeing the signature box correctly. In a previous email you speculated that the issue could be stemming from an OS update that occurred within SHA, is that something you could investigate or test further? If we are able to identify the source of the issue, I can talk to developers about what solutions might exist. But as of now, I’m not seeing the same issues in any of my investigation.

Perhaps you could look into the OS as well as browser versions on your end and report back if that leads us anywhere?

In the meantime I will log the issue in GitHib so that it is saved, while we coordinate to investigate further.

 
![image](https://cloud.githubusercontent.com/assets/4098544/5938202/ab960524-a6c6-11e4-9ed0-951d056b48db.png)

**Comment by slmessier** [comment]
This issue has been tested against the client browser, as well as the hosting environment and it can be concluded that **this issue is likely stemming from the production hosting environment.** 

All tests have **executed utilizing the following Inspection Record:**
![image](https://cloud.githubusercontent.com/assets/4098544/5982237/22c68b7c-a88f-11e4-90af-874a29cf9f40.png)

Please see the **results of the testing below:**
![image](https://cloud.githubusercontent.com/assets/4098544/5983282/f08bfaba-a899-11e4-8f39-0128146fdea5.png)

Example of **reduced signature box size below:**
![image](https://cloud.githubusercontent.com/assets/4098544/5982342/f7dcf706-a88f-11e4-9568-07a28309ee00.png)

**Comment by kanglu666** [comment]
fixed in SHA PROD.

**Comment by slmessier** [comment]
validated as successful in SHA PROD. Assigning to Tad for confirmation and close-out.

**Comment by Tad-Daniel** [comment]
Issue appears to have been corrected.
